### ISSUE TITLE
Bitcask fails to start after server runs all day

### ISSUE THREAD

**Issue by osiloke** [basho/riak_kv#1045]
Hi,
I'm working on a system which continuously processes images from live tv. I'm in the process of trying out different nosql dbs for storing metadata and i'm currently on riak. I have a problem where the riak cluster crashes after running for a couple of hours collecting metadata. It seems to be due to bitcask not being able to load the indexes. I have no experience with erlang so i cant make sense of the log but will appreciate it if someone can make sense of this.

The error log is here https://gist.github.com/osiloke/5b3e6f56dec3d7cab60e

**Comment by engelsanchez** [comment]
Hi @osiloke. Would you mind telling us what version of Riak you are using? Also, would you mind attaching more information like: is the disk full? Were there any errors in the logs prior to this one? There should be, as this one indicates some error happened repeatedly to the point it gave up opening the files.

**Comment by osiloke** [comment]
Hi, i'm running the latest riak version (2.0.2) as instructed here, http://docs.basho.com/riak/latest/ops/building/installing/debian-ubuntu/#Advanced-apt-Installation, on ubuntu 14.04. The disk isn't full. I switched to eleveldb as a backend and it's been running smooth all day with only one node as opposed to when i used bitcask with two nodes although the memory seems to be gradually filling up but i think thats in accordance with the 70% cache setting for eleveldb. Here are some more error logs

2014-11-14, this seems to be related to ulimit
https://gist.github.com/osiloke/64889e4ece50079082c8

2014-11-15
https://gist.github.com/osiloke/af15e2755a136a77ee81

Thanks

**Comment by engelsanchez** [comment]
Ah, yes. You will hit problems with any of our backends eventually if you don't give it a high ulimit. Riak is probably showing the ulimit warning when you start it and in the log files.  This is annoying but standard with database software, which is normally file handle hungry. Make sure you follow the recommendations in the docs http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/

I'm closing this ticket now. Feel free to re-open if you find evidence that this is not the root of the problem.

**Comment by osiloke** [comment]
Yeah, next time i'll look far into the log. Thank you very much sir
