### ISSUE TITLE
Error when updating statistic. [JIRA: RIAK-1747]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_kv#1051]
Customer ticket 9572

```
2014-11-21 00:35:04.595 [warning] <0.561.0>@riak_kv_stat:perform_update:99 error:{badmatch,[]} updating stat {riak_object_merge,riak_kv_pncounter,277}.
```

Riak version 2.0.2 using a counter CRDT.

**Comment by russelldb** [comment]
Do you think this is dealt with by 2.0.3 and exometer @jburwell ?

**Comment by russelldb** [comment]
Is it the same issue?

**Comment by jburwell** [comment]
I will check the r_t verify_riak_stats test case to see if pn counter stats are verified.

/cc @uwiger

**Comment by DSomogyi** [comment]
Comment for Jira.
