### ISSUE TITLE
Quick question on riak_kv_pb_mapred

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_kv#1054]
Looks like [this head](https://github.com/basho/riak_kv/blob/2.0/src/riak_kv_pb_mapred.erl#L146-L162)

``` erlang
process_stream({'DOWN', Ref, process, Pid, Reason}, Ref,
               State=#state{req=#rpbmapredreq{},
                            req_ctx=#pipe_ctx{sender={Pid, Ref}}=PipeCtx}) ->
```

is never called as the second argument is actually `ReqId` in riak_api sense, as the `process` function is [returning PipeRef](https://github.com/basho/riak_kv/blob/2.0/src/riak_kv_pb_mapred.erl#L209) and then never matches with the monitor reference, even when the pipe input sender crashes. And then sender error or normal finish all fall through to the final ignored head of `process_stream/3`. So maybe this head should be like this in theory?:

``` erlang
process_stream({'DOWN', Ref, process, Pid, Reason}, PipeRef,
               State=#state{req=#rpbmapredreq{},
                            req_ctx=#pipe_ctx{ref=PipeRef, sender={Pid, Ref}}=PipeCtx}) ->
```

This is likely not the cause of the problem I'm currently investigating, but I just found when reviewing codes.

**Comment by krestenkrab** [comment]
It looks like you're right. The parameter you call `PipeRef` is called `ReqId` in the previous head - https://github.com/basho/riak_kv/blob/2.0/src/riak_kv_pb_mapred.erl#L106-L113.  

Would this be catchable by adding some extra type specs?  Looks a little tricky.

**Comment by kuenishi** [comment]
Maybe changing PipeRef to something other than `reference()`, like `{pipe, reference}` makes dialyzer happy, but I just don't know the code impact. If `ReqId` stuff for riak_pb_api_service is opaque, then that might work.

Oh, I just found riak_api_pb_service is using old-style behaviour_info definition. Maybe changing to this style (not sure this works..) ?

``` erlang
-callback init() -> {ok, term()} | {error, term()}.
-callback decode(integer(), binary()) -> {ok, msg_record()} | {error, term()}.
-callback encode(msg_record()) -> {ok, binary()} | {error, term()}.
-callback process(msg_record()) -> {reply, {stream, req_id(T)}} | ... | {error, term(), state()}.
-callback process_stream(msg_record(), req_id(T), state()) -> ....
```

**Comment by seancribbs** [comment]
@kuenishi Do you have an outdated version? [2.0](https://github.com/basho/riak_api/blob/2.0/src/riak_api_pb_service.erl#L178) and develop have proper new-style callback annotations.

**Comment by kuenishi** [comment]
@seancribbs Oh, that was me reading 1.4 code bases.

**Comment by kuenishi** [comment]
Direct fix for this is opened as #1073. But even in 2.0 latest branch there are no way to catch this by dialyzer. Because callback type/specs in `riak_pb_api_service` is specifying just `term()` for request id and that's all given by the callback interface. One easy solution for this is to restrict `ReqId` as only for reference in callbacks like:

``` erlang
-callback process(Message :: term(), State :: term()) ->
    {reply, ReplyMessage :: term(), NewState :: term()} |
    {reply, {stream, ReqId :: reference()}, NewState :: term()} |
    {error, Error :: process_error(), NewState :: term()}.
```

But this is somewhat backwards incompatible in dialyzer. Thoughts?

**Comment by seancribbs** [comment]
We can't narrow that type to `reference()` because many of the KV FSMs use integers for the `ReqId` term.

**Comment by kuenishi** [comment]
Goof. Closing, waiting for Erlang and dialyzer support templates parameters like C++ to restrict types :trollface:
