### ISSUE TITLE
json api seems to artifically limit the datatypes assignable to the register datatype? [JIRA: RIAK-1641]

### ISSUE THREAD

**Issue by jisaacstone** [basho/riak_kv#1095]
https://github.com/basho/riak_kv/blob/2.0/src/riak_kv_crdt_json.erl#L49

> -type register_op() :: {assign, binary()}.

registers can be assigned any erlang term (seems)

tested just now in 2.0.5

`riak attach`

``` erlang
(riak@127.0.0.1)12> O1 = riak_kv_crdt:new({<<"item">>,<<"text">>}, <<"1">>, riak_dt_map).
{r_object,{<<"item">>,<<"text">>},
          <<"1">>,
          [{r_content,{dict,1,16,16,8,80,48,
                            {[],[],[],[],[],[],[],[],[],[],[],[],[],[],...},
                            {{[],[],[],[],[],[],[],[],[],[],[[...]],[],...}}},
                      <<69,2,0,0,0,11,114,105,97,107,95,100,116,95,109,97,112,
                        77,1,131,104,...>>}],
          [],
          {dict,1,16,16,8,80,48,
                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],...},
                {{[],[],[],[],[],[],[],[],[],[],[[<<...>>|...]],[],[],...}}},
          undefined}
(riak@127.0.0.1)10> O2=riak_kv_crdt:update(O1, <<"r">>, {crdt_op, riak_dt_map, { update, [ {update, {<<"foo">>, riak_dt_lwwreg}, {assign, 7}} ] }, undefined }).
{r_object,{<<"item">>,<<"text">>},
          <<"1">>,
          [{r_content,{dict,1,16,16,8,80,48,
                            {[],[],[],[],[],[],[],[],[],[],[],[],[],[],...},
                            {{[],[],[],[],[],[],[],[],[],[],[[...]],[],...}}},
                      <<69,2,0,0,0,11,114,105,97,107,95,100,116,95,109,97,112,
                        77,1,131,80,...>>}],
          [],
          {dict,1,16,16,8,80,48,
                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],...},
                {{[],[],[],[],[],[],[],[],[],[],[[<<...>>|...]],[],[],...}}},
          undefined}
(riak@127.0.0.1)11> riak_kv_crdt:map_value(O2).
[{{<<"foo">>,riak_dt_lwwreg},7}]
```

Anyway they ought to be consistent and I looked at the source & could not see any reason why numbers (or other things) can't be assigned to a register.

So looks like a bug.

I feel this ought to work:

> $ curl -i -XPOST http://localhost:8098/types/item/buckets/default/datatypes/1 -H"Content-Type: >application/json" -d'
>  {
>    "update": {
>    "price_register": 12}}'
> HTTP/1.1 400 Bad Request
> Vary: Accept-Encoding
> Server: MochiWeb/1.1 WebMachine/1.10.5 (jokes are better explained)
> Date: Sat, 21 Mar 2015 06:58:21 GMT
> Content-Type: text/plain
> Content-Length: 45
> 
> Invalid operation on datatype 'register': 12

Can I get confirmation? I don't mind to try my hand at fixing it myself, but as I only recently started learning Erlang I'll be asking you all to doublecheck everything. Cool?

**Comment by seancribbs** [comment]
This is correct, and intentional; we limit the acceptable values that can be stored in registers and sets to binaries so that we can be consistent across both client interfaces. You should not be using the datatypes directly on the Riak node, but via a client. Serialize whatever data you want into a binary (string in JSON) as the value of the register.

**Comment by Basho-JIRA** [comment]
[~seancribbs], can this be closed? 

**_[posted via JIRA by Derek Somogyi]**_
