### ISSUE TITLE
vnode status file can cause a riak node to fail to start [JIRA: RIAK-1717]

### ISSUE THREAD

**Issue by russelldb** [basho/riak_kv#1103]
https://github.com/basho/riak_kv/blob/develop/src/riak_kv_vnode_status_mgr.erl#L333

Due to changes in unicode semantics in r17, the vnode status manager file, after storing a random binary as vnode id, may fail to be read with `file:consult` as the vnode id binary is not valid text. 

This _MUST_ be fixed before erlang r17 is supported.

However, this is a specific case of a more general problem of file corruption causing riak to fail to start. A corrupt, unreadable file should be thrown away, and a new vnodeid+counter created (and message logged.)

NOTE: this is not a new issue, but exists for pre kv679 fix code too.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_kv/issues/1103 

**_[posted via JIRA by Deborah Rakow]**_

**Comment by Basho-JIRA** [comment]
Jon M confirmed code merged to 2.0.6 on 6/25/15.  Dev is done. Now just waiting to go into additional releases.  

**_[posted via JIRA by Patricia Brewer]**_
