### ISSUE TITLE
Inconsistent Hashing of Metadata Dict [JIRA: RIAK-2193]

### ISSUE THREAD

**Issue by ian-mi** [basho/riak_kv#1189]
As the internal representation of the dict data structure is not defined it is not guaranteed to have a unique representation. Therefore hashing identical dicts can lead to differing results. When this occurs, AAE will attempt to trigger read repair but the object is never repaired because its vclock does not differ leading to endless AAE churn.

Jira issue: [RIAK-2043]

**Comment by Basho-JIRA** [comment]
related - https://gist.github.com/andytill/e00f173e52aeb9ab64ca 

***[posted via JIRA by Bryan Hunt]***

**Comment by Basho-JIRA** [comment]
related - https://gist.github.com/andytill/e00f173e52aeb9ab64ca 

***[posted via JIRA by Bryan Hunt]***

**Comment by Basho-JIRA** [comment]
gist also available 

***[posted via JIRA by Bryan Hunt]***

**Comment by Basho-JIRA** [comment]
https://basho.zendesk.com/agent/tickets/11958

Possibly related - and possibly related to Yokozuna endlessly repairing the same keys,

https://gist.github.com/andytill/e00f173e52aeb9ab64ca

https://basho.zendesk.com/agent/tickets/12005
 

***[posted via JIRA by Bryan Hunt]***

**Comment by ian-mi** [comment]
It is my belief that the hash comparisons should match the comparisons done in the get FSM in order to trigger read repair. As the get FSM only uses the vclock to trigger read repair, I  think it makes sense for AAE to only hash the vclock. As riak_object:hash already pulls out the vclock and sorts it to give a canonical vclock, we could do the same and simply pass the sorted vclock alone to the hash function.

**Comment by jonmeredith** [comment]
I think you need vclock plus dots, but in principle yes.
We got burned by bugs with an early customer where we were generating the
same vclock for two different events so I would rather decouple the
mechanism.

Don't forget we have write once data and last_write_wins stuff going on too
- that makes it more robust.

**Comment by russelldb** [comment]
I think it's a great idea, but it only counts for post per-key-actor-epoch version vectors. Before then we could conceivably have two VVs that mean totally different histories.

We need a quick fix/workaround, but medium term this canonical hash needs to be considered in whatever new object format we come up with.

**Comment by jonmeredith** [comment]
Canonical hash absolutely has to be considered in object format and any
payloads that use it.

**Comment by Basho-JIRA** [comment]
I believe these issues refer to the same problem. 

**_[posted via JIRA by Nicholas Bellerophon]**_

**Comment by nerophon** [comment]
This github issue is, I believe, in JIRA as both a critical bug and a major story:
https://bashoeng.atlassian.net/browse/RIAK-2043
https://bashoeng.atlassian.net/browse/RIAK-2193

**Comment by Basho-JIRA** [comment]
Added the label of 2.2 so we can track it in our 2.2 discussions and Kanban.  Did not put in the fix version of 2.2.0 until we have a sense that it will go in that release.  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment]
The plan is still to release a patch as well as the feature with 2.2 Two issues have delayed the patch:
1. We've identified an issue with pre 2.1 data where data will become permanently irreparable with the new hashing scheme. We need to use the old hashing scheme and the read repair code to do a full sweep before a user upgrades to the new hashing. This code is complete but not yet reviewed.
2. The hashtree format needs to be set for the patch and 2.2 before we release. We do not want patched users to have to go through another round of tree rebuilds upon upgrade to 2.2. The hashtree format needs to be changed so that we can support safe downgrades. This code is in progress. 

**_[posted via JIRA by Brian Sparrow]**_

**Comment by binarytemple-external** [comment]
@bsparrow435 is this still due for inclusion with 2.2 ?

**Comment by ghost** [comment]
Hmm. Unclear what action was taken in relation to this issue.

**Comment by bsparrow435** [comment]
Hey Bryan the fix for this was included in Riak 2.2 with the launch of the new aae version.

**Comment by ghost** [comment]
Thanks @bsparrow435 !
