### ISSUE TITLE
riak_kv memory backend has very likely a memory leak  [JIRA: RIAK-2240]

### ISSUE THREAD

**Issue by jonasrichard** [basho/riak_kv#1238]
When using memory backend with TTL defined, and if we get a key which is stale (according to the TTL value), the code removes the objects from the DataRef and IndexRef tables but not from the TimeRef (time index) ETS table.

https://github.com/basho/riak_kv/blob/b107be2e6c4135eaeeca98f0350f41cbb9033bce/src/riak_kv_memory_backend.erl#L183

It can be seen after executing an `ets:i()`:

```
8913019 riak_kv_342539446249430371453988632667878832731859189760_t ordered_set 686755 18216874 <0.1034.0>
9175164 riak_kv_342539446249430371453988632667878832731859189760_i ordered_set 0 89 <0.1034.0>
9437309 riak_kv_342539446249430371453988632667878832731859189760 ordered_set 2806 108204 <0.1034.0>

9699454 riak_kv_57089907708238395242331438777979805455309864960_t ordered_set 787823 20928003 <0.1029.0>
9961599 riak_kv_57089907708238395242331438777979805455309864960_i ordered_set 0 89 <0.1029.0>
10223744 riak_kv_57089907708238395242331438777979805455309864960 ordered_set 2884 111145 <0.1029.0>
...
```

787823 records in the _t table versus 2884 records in the data table.

UsedMemory state seems to be well handled.

**Comment by jonasrichard** [comment]
Please check this branch, in theory it fixes the issue.

https://github.com/jonasrichard/riak_kv/tree/fix_riak_kv_1238

**Comment by jonmeredith** [comment]
Thanks @jonasrichard sorry this has sat for so long.

**Comment by macintux** [comment]
Trivial automated test passes, code looks good. I believe the extra `time_entry/4` function clause to be unnecessary because the logic leading to that invocation will not permit an undefined `TimeRef` value, but the `put` function is sufficiently murky it's a good idea to include it anyway.

My hope is to do some additional cleanup on the module to make the logic much easier to follow, but this patch is most helpful.

**Comment by jonasrichard** [comment]
Sounds great. Yeah, I found traces of history of ideas in the code, but that is the way it goes.

**Comment by nerophon** [comment]
I believe this is similar to or a duplicate of #1064, and finally fixed in branch:
https://github.com/basho/riak_kv/tree/hotfix/2.0.6-memory_backend_ets_leaks

**Comment by jonasrichard** [comment]
Yes, think so. I am closing this.
