### ISSUE TITLE
Error in TsGetReq when invalid data passed in key [JIRA: RIAK-2267]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_kv#1257]
Using the following table def:

```
riak-admin bucket-type create GeoCheckin '{"props": {"n_val": 3, "table_def": "CREATE TABLE GeoCheckin (geohash varchar not null, user varchar not null, time timestamp not null, weather varchar not null, temperature double, PRIMARY     KEY((geohash, user, quantum(time, 15, m)), geohash, user, time))"}}'
```

If you make a `TsGetReq` with a `TsCell` whose `double_value` is set for the `time` parameter as opposed to using `integer_value`, Riak will return a `badarith` error.

Expected: Riak TS should validate that keys passed to it for `TsGetReq` and `TsDelReq` have the correct count of `TsCell` values and that the data in the cells are as expected. If not, a friendly error string and error code should be returned.

**Comment by Basho-JIRA** [comment]
PR:
https://github.com/basho/riak_kv/issues/1257 

**_[posted via JIRA by Derek Somogyi]**_
