### ISSUE TITLE
w1c remaining timeout calculation mistake [JIRA: RIAK-2317]

### ISSUE THREAD

**Issue by jonmeredith** [basho/riak_kv#1293]
The remaining w1c timeout calculation works out the elapsed time in microseconds then forgets to convert to milliseconds before adjusting the timeout.  Noticed when I added so much debug logging to track down something else it started to trip in batch sizes of 300.  

https://github.com/basho/riak_kv/blob/end-to-end/timeseries/src/riak_kv_w1c_worker.erl#L399

```
remaining_put_timeout(Start, Timeout) ->
    non_neg(Timeout -
                non_neg(trunc(timer:now_diff(os:timestamp(), Start)))).
```

Would recommend a fix like this

```
remaining_put_timeout(Start, Timeout) ->
    non_neg(Timeout -
                non_neg(timer:now_diff(os:timestamp(), Start) div 1000)).
```

**Comment by Basho-JIRA** [comment]
[~dsomogyi] MUSTFIX for 1.0 

**_[posted via JIRA by Jon Meredith]**_

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_kv/pull/1295 

**_[posted via JIRA by John Daily]**_
