### ISSUE TITLE
a/sync_put mashup [JIRA: RIAK-2329]

### ISSUE THREAD

**Issue by erikleitch** [basho/riak_kv#1307]
As a knock-on effect of last-minute performance changes, we have created a bizarre situation where TS W1C path with async_put=true now calls down to eleveldb:sync_put, which is really actually a synchronous put, and async_put=false calls down to eleveldb:put, which is not actually a synchronous put at all

This should be sorted out for TS1.1:  
- async_put=true should call down to eleveldb:async_put
- async_put=false should call down to eleveldb:sync_put
- We need to resolve whether vnode stats should be disabled on both calls, or whether vnode stats updates will be improved on TS1.1 timescales so they can be restored
- We should default async_put to the mode that gives us the best performance
- We should update the relevant documentation to make it clear what settings are required for the best performance

**Comment by Basho-JIRA** [comment]
Comments in  https://github.com/basho/riak_kv/pull/1320 

**_[posted via JIRA by Erik Leitch]**_

**Comment by Basho-JIRA** [comment]
Closing this as it has been deferred to TS 1.2 or after.  RTS-820 has been created for "picking this work back up" and is currently targeted for TS 1.2 release. 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by Basho-JIRA** [comment]
[~kclark] 

**_[posted via JIRA by Korrigan Clark]**_

**Comment by Basho-JIRA** [comment]
[~brett] 

**_[posted via JIRA by Korrigan Clark]**_

**Comment by Basho-JIRA** [comment]
Reopening per a discussion with Brett.  Required for the KV/TS Merge.  Includes code cleanup. 

***[posted via JIRA by Derek Somogyi]***

**Comment by Basho-JIRA** [comment]
New, updated PR with Erik's comments: https://github.com/basho/riak_kv/pull/1628 

***[posted via JIRA by Brett Hazen]***

**Comment by Basho-JIRA** [comment]
New, updated PR with Erik's comments: https://github.com/basho/riak_kv/pull/1628. However, this does not seem to be the final solution.  More discussion underway. 

***[posted via JIRA by Brett Hazen]***

**Comment by Basho-JIRA** [comment]
Looks like this will be superseded by MvM's non-blocking write work: 
- https://github.com/basho/riak_kv/pull/1632
- https://github.com/basho/eleveldb/pull/222
- https://github.com/basho/leveldb/pull/212 

***[posted via JIRA by Brett Hazen]***

**Comment by Basho-JIRA** [comment]
New, updated PR with Erik's comments: -https://github.com/basho/riak_kv/pull/1628-. However, this does not seem to be the final solution.  More discussion underway. 

***[posted via JIRA by Brett Hazen]***
