### ISSUE TITLE
API crash: mishandling of some atom error responses in Riak TS PB/TTB service. [JIRA: RIAK-2556]

### ISSUE THREAD

**Issue by emauton** [basho/riak_kv#1418]
For riak-ts_1.3.0-1_amd64.deb from http://docs.basho.com/riak/ts/1.3.0/downloads/

Throwing some basho_bench load at Riak TS, I get lots of 'disconnected'. Looking at Riak TS itself, the PB server is crashing on a `badarg`:

```
2016-05-13 10:51:34.969 [error] <0.988.0> gen_fsm <0.988.0> in state connected terminated with reason: {error,badarg,[{erlang,iolist_to_binary,[overload],[]},{riak_kv_ts_svc,make_rpberrresp,2,    [{file,"src/riak_kv_ts_svc.erl"},{line,483}]},{riak_kv_ts_svc,sub_tsqueryreq,4,[{file,"src/riak_kv_ts_svc.erl"},{line,445}]},{riak_api_pb_server,process_message,4,[{file,"src/riak_api_pb_server.erl"},{line,388}]},{riak_api_pb_server,connected,2,[{file,"src/riak_api_pb_server.erl"},{line,226}]},{riak_api_pb_server,decode_buffer,2,[{file,"src/riak_api_pb_server.erl"},{line,364}]},{gen_fsm,handle_msg,7,[{file,...},...]},...]}
```

This is the atom `overload` not being translated and dropping off the end of the case at 
  https://github.com/basho/riak_kv/blob/2.1.3-ts/src/riak_kv_ts_svc.erl#L445

Similarly for the error atom `no_primaries_available`, probably some others.

An "atom catchall" at L443 along these lines would fix this and similar crashes while communicating something useful to the user:

```
{error, Reason} when is_atom(Reason) ->
    {reply, make_rpberrresp(?E_SUBMIT, atom_to_list(Reason)), State};
```

Thanks!

**Comment by point9repeating** [comment]
I have seen the same thing happening. We will get an error message from our client that says "no response from backend". If I look at the riak error and crash logs, I see exceptions like the following:

`{{error,badarg,[{erlang,iolist_to_binary,[overload],[]},{riak_kv_ts_svc,make_rpberrresp,2,[{file,"src/riak_kv_ts_svc.erl"},{line,483}]},{riak_kv_ts_svc,sub_tsqu
eryreq,4,[{file,"src/riak_kv_ts_svc.erl"},{line,445}]},{riak_kv_pb_ts,process,2,[{file,"src/riak_kv_pb_ts.erl"},{line,71}]},{riak_api_pb_server,process_message,4,[{file,"src/riak_a
pi_pb_server.erl"},{line,388}]},{riak_api_pb_server,connected,2,[{file,"src/riak_api_pb_server.erl"},{line,226}]},{riak_api_pb_server,decode_buffer,2,[{file,"src/riak_api_pb_server
.erl"},{line,364}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,505}]}]},[{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,622}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib
.erl"},{line,239}]}]}`

**Comment by lukebakken** [comment]
@angrycub a fix should be planned for 1.4

**Comment by binarytemple-external** [comment]
1.4 was released in August, might do with a fix version label.

**Comment by Basho-JIRA** [comment]
Addressed in:
* https://github.com/basho/riak_kv/pull/1544
* https://github.com/basho/riak_test/pull/1204 

***[posted via JIRA by James Gorlick]***
