### ISSUE TITLE
Riak TS: Performing single row fetches sometimes results in "timeout" [JIRA: RTS-1328]

### ISSUE THREAD

**Issue by alexmoore** [basho/riak_kv#1464]
Sometimes when performing a single row fetch operation over the TTB interface, I get back the error "timeout" with code 1010. 

The issue seems to resolve itself fairly quickly, as subsequent fetches and queries will pull back the row successfully.  

Probably EC in action, but a more descriptive error message would be better. 

Will update issue with a reproducer test link.

**Comment by alexmoore** [comment]
See https://github.com/basho/riak-java-client/blob/kv-1464-reproducer/src/test/java/com/basho/riak/client/api/commands/itest/ITestTimeSeriesFetchBug.java for a reproducer test.  

Test can be run with:
`mvn test -Dtest=ITestTimeSeriesFetchBug -Dcom.basho.riak.pbcport=10017 -Dcom.basho.riak.timeseries=true`

May take many runs to reproduce, have had more success with larger devrel clusters (4-5 devrel nodes).

**Comment by alexmoore** [comment]
Error is thrown here: https://github.com/basho/riak_kv/blob/a1ba1f4bad805a9e043b43495a74dac1d05267a8/src/riak_kv_ts_svc.erl#L309-L310

**Comment by Basho-JIRA** [comment]
Fix pushed to https://github.com/basho/riak_kv/pull/1466 

**_[posted via JIRA by Andrei Zavada]**_

**Comment by Basho-JIRA** [comment]
Following a discussion, it was decided to disallow 0 for a timeout value (and thus, no 'infinity') in get, delete and list_keys API calls. No change is required in riak_kv; and [~amoore] will take care of diagnosing and handling this situation in clients. 

**_[posted via JIRA by Andrei Zavada]**_
