### ISSUE TITLE
Index hashtree upgrade could stall if node added at specific time [JIRA: RIAK-2976]

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak_kv#1537]
If a new node is added to the cluster after the index_hashtree upgrade has started or finished and the new node has legacy trees, the new node could end up in a situation where the trees will never upgrade. Should add a check here: https://github.com/basho/riak_kv/blob/develop-2.2/src/riak_kv_entropy_manager.erl#L689 to check the remote nodes pending_version and version and if either is NOT legacy, go ahead and start the upgrade.

**Comment by Basho-JIRA** [comment]
Brian has a fix just hasn't PRd yet.   

***[posted via JIRA by Patricia Brewer]***

**Comment by Basho-JIRA** [comment]
Addressed with https://github.com/basho/riak_kv/commit/354ed7d353f06eab472d53677551edcdada296d3 

***[posted via JIRA by Brian Sparrow]***
