### ISSUE TITLE
Commit hook not called when set on bucket type [JIRA: RIAK-2988]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_kv#1541]
See the following riak-users message:

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2016-November/018839.html

Entire thread:

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2016-November/018827.html

**Comment by mav4001** [comment]
This seems to happen only on 2.0.x versions
In Version 2.1.4 the hooks are called with just a {bucket-type,object} tuple for buckets of a type, and a single argument Object for buckets that are not of a type

**Comment by bsparrow435** [comment]
Fixed on 2.0 and 2.2
