### ISSUE TITLE
How can i use recon lib in riak? [JIRA: RIAK-3402]

### ISSUE THREAD

**Issue by ghost** [basho/riak_kv#1647]
As we know that riak is bulid on erlang. I want parse the performance about the riak processes. eg: the most binary memory occupied by which process. And the recon can provide the ability. So who know  how the recon uesed in riak erl vm machine.

**Comment by andytill** [comment]
Hi @alisawangJJ, recon can be added to a running VM by [attaching](http://docs.basho.com/riak/kv/2.2.3/using/admin/riak-cli/#attach) a shell and then calling the [code:add_path/1](http://erlang.org/doc/man/code.html#add_path-1) function, the dir should be recon's ebin directory after compilation, it may have to be the absolute path. recon modules will then be available from the shell on that node.

The path to recon will still be added after the shell has detached.

Basho has done no official testing with recon AFAIK so I'd advise not to use it on a production instance.

**Comment by lukebakken** [comment]
Thanks @andytill 

Another option would be to add `recon` to the `basho-patches` directory. This directory is usually `/usr/lib/riak/lib/basho-patches` or `/usr/lib64/lib/basho-patches`, and is added to the code path when Riak starts.

**Comment by ghost** [comment]
The question had been resolved. thank you two very much!
