### ISSUE TITLE
 binary_alloc: Cannot allocate 1345022656 bytes of memory (of type "binary"). [JIRA: RIAK-3403]

### ISSUE THREAD

**Issue by ghost** [basho/riak_kv#1648]
I have a 35 nodes riak cluster. After add 12 new nodes to the cluster ,My system report erl_crash.dump very often. Most of them said " binary_alloc: Cannot allocate xxxxx bytes of memory (of type "binary")." 
In console.log and error.log I found lots of log like below. 
Is there any way to parse how it hanpped ? Or anyone knows what's the reson about this? 

 Put failure: too many siblings for object <<48,111,58,36,52,110,27,80,6,102,7,5,154,243,110,59,104,75,36>>/<<"104cfcc6-4900-3a92-ad79-cd0d98c8ab5f">> (101)
@riak_kv_vnode:encode_and_put:2145 Put failure: too many siblings for object <<48,98,58,36,52,110,27,80,6,102,7,5,154,243,110,59,104,75,36>>/<<69,29,85,106,107,184,67,197,154,233,39,180,166,195,40,135,0,0,0,0>> (101)

**Comment by russelldb** [comment]
@alisawangJJ suggest you try the riak-user mailing list in the first instance http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com. Looks like "sibling explosion" at first guess…what version of riak are you using? But like I say, better/faster response on the mailing list, and then _if_ there as an issue with riak_kv, it would be time to open one.

**Comment by lukebakken** [comment]
Thanks @russelldb 

@alisawangJJ - this is your problem:

> Put failure: too many siblings for object

You must ensure that conflicts are resolved. There is [documentation on conflicts](http://docs.basho.com/riak/kv/2.2.3/developing/usage/conflict-resolution/) and [documentation](http://docs.basho.com/riak/kv/2.2.3/developing/getting-started/) for each client library.

**Comment by ghost** [comment]
@lukebakken  @russelldb  thank you guys.
I changed the configuration  "bucktes.default.merge_statrgey = 2"  then the problem seems have been resolved. And I want to know  what scene will lead to "sibling explosion" ?Does the add nodes event cause "sibling explosion" ?and my "object.size.maximum=50m" but i see lots of logs say"put very large object....." whick object size greater than 50m?
