### ISSUE TITLE
Remove erlang_js before releasing riak 2.2.6 

### ISSUE THREAD

**Issue by ghost** [basho/riak_kv#1669]
There is nobody (to the best of my knowledge) using this functionality for several years now, but the dependency persists. 

The dependency bundles and compiles several of it's dependencies, such as spidermonkey, nspr, and the quizzically named 'system'. These libraries are provided as standard on all contemporary Linux distributions and can be installed easily on OSX using 'brew'.

Anyway, nobody uses it, and it's currently failing to compile on Freebsd 11 ([gist](https://gist.github.com/bryanhuntesl/461c8d59e03b5b03d21ede3a1f334081)).

I propose we remove erlang_js from riak_kv, and take a step towards reducing needless complexity.

**Comment by Licenser** [comment]
https://github.com/basho/erlang_js/pull/67 Should fix the readline issue on FreeBSD

**Comment by ghost** [comment]
Tested @Licenser patch and can confirm it works - would be nice to apply it as a stopgap measure to fix the freebsd build before beginning the work to purge erlang_js from the codebase.

**Comment by jadeallenx** [comment]
kill it with cleansing fire 

cc @cmeiklejohn

**Comment by llelf** [comment]
How about before 3.0?
I will help with the exorcism.

**Comment by cmeiklejohn** [comment]
It's already been removed in the develop-3.0 build of Riak we are working on.

**Comment by martinsumner** [comment]
Removed in 3.0
