### ISSUE TITLE
Make tests write data to different directories

### ISSUE THREAD

**Issue by ThomasArts** [basho/riak_kv#1685]
When using rebar3 instead of rebar for building riak_kv in develop-3.0, then files are written in the top level directory. Instead, they should be written somewhere relative to _build/test directory, which is ignored in .gitignore.

**Comment by martinsumner** [comment]
I think I've resolved this on `develop-3.0-merge` (on my repo) - the branch which combines `develop-3.0` and develop-2.9`.

See https://github.com/martinsumner/riak_kv/commit/d6f642051128505d21f774bae91249ba36ce22c9

plus this:

https://github.com/martinsumner/riak_kv/commit/2d8f00a73bc3841c0ce2986be724ba96873da839
