### ISSUE TITLE
Automated full-sync with Tictac AAE

### ISSUE THREAD

**Issue by martinsumner** [basho/riak_kv#1691]
Tictac AAE was introduced in 2.9.0, which allowed for the use of AAE in full-sync co-ordination between clusters with:

- no pausing for (or failures due to) rebuilds;
- support for full-sync between different ring_size;
- support for per-bucket full-sync;
- support for use of cached entropy trees (all bucket full-sync) or modified date range full-sync (per bucket) to improve efficiency.

However, using this feature requires the customer to control and manage the full-sync process using the `kv_index_tictactree` `aae_exchange` module, and the `aae_fold` api.  There was no default, automated way of adding full-sync between clusters through configuration.

This issue is a feature request to provide the default automated full-sync through configuration.

**Comment by martinsumner** [comment]
The proposed configuration for full-sync is to be built on the following principles and constraints:

- Each node in the cluster will be independently configured to act as a source for full-sync replication.  There will be no cluster-wide co-ordination of full-sync (and associated election of leaders and fallback handling).  This proposal is intended to reduce complexity.

- Any node in a cluster can be configured to be a source for full-sync replication to no more than one sink cluster.  To sync with multiple clusters, different nodes within the source cluster will need to be pointed at different sinks.

- Preventing excessive overlapping of full-sync activity will be managed by random jittering of activity and deliberate spacing of activity (so that in a given time period, there will be N slots, and node N will trigger any activity within the Nth slot).

- Nodes should skip activity when previous activity over-runs.

- Work will not be re-allocated on failure, if a node fails its full-sync work will not be handed off to another node.  There will be less full-sync activity in the cluster - the node configurations must account for the possibility of failure to ensure "enough" synchronisation occurs even under failure conditions.

- There will be no configuration required to act as a sink for full-sync, other than the enabling of Tictac AAE.

- Full-sync for a node can be for either a list of buckets or for all data.  Where a bucket list is used, only a single bucket will be sync'd each period, and each bucket will be allocated an equal number of periods.  The configuration will allow for control over how many periods are allocated to sync-checking recent changes, and how many are allocated for sync-checking historic changes.

**Comment by martinsumner** [comment]
Proposed configuration elements:

> Enable/disable full_sync

``ttaaefs_active: on|off``

> Set the scope of full_sync for this node, will it try and full_sync all the data or just a list of buckets (note that full_sync of a bucket list is likely to be less efficient than all data in most circumstances)

``ttaaefs_scope: all|bucket_list``

> Provide a list of {Type, Bucket} tuples if bucket_list is to be used

``ttaaefs_bucketlist: [{Type, Bucket}]``

> Through which IP can the sink be reached.  This could be a NAT'd IP, the IP of a load-balancer, or the IP of an individual node.  If the source IP is unreachable (i.e. the node does not respond to riak ping), then no sync will be attempted.  If configuring with node specific nodes ensuring diversity of sink node IPs to allow for resilience to failure is an operator responsibility.

``ttaaefs_peerip: <<ip_addr>>`` 

> Port for reaching sink node

``ttaaefs_port:  port#``

> Protocol for using aae_fold

``ttaaefs_protocol:  http:pb``

> The day will be divided into 100 equal periods, and each period into N equal slots (with N being determined by each node at the start of the period based on the number of up Nodes in the sink cluster).  For all-bucket full-sync, the number of periods in which this node will not check for synchronisation, and the number of periods which this node will check for synchronisation across all data need to be configured.  For per-bucket full-sync, the number of periods which this node will check for synchronisation for data modified in the past hour, and the number of periods for which this node will check for synchronisation for data modified in the past day also need to be set.

> The total number of slots set across all settings within this node must equal 100. 

``ttaaefs_nocheck: 0 - 100``

> The all check value should be set to a low number for efficiency when using per-bucket synchronisation

``ttaaefs_allcheck: 0 - 100``

> Number of checks focusing on data modified in the past hour (bucket-list full-sync only)

``ttaaefs_hourcheck: 0 - 100``

> Number of checks focusing on data modified in the past day (bucket-list full-sync only)

``ttaaefs_daycheck: 0 - 100``

**Comment by martinsumner** [comment]
https://github.com/martinsumner/riak_kv/compare/develop-2.9...martinsumner:mas-i1691-ttaaefullsync

Work in progress.  this has been subject to manual testing, focus on automated testing now.

**Comment by martinsumner** [comment]
One issue is how to re-queue when a mismatch is discovered.  

We can call the rt_enqueue HTTP API (from within riak_repl).  This would mean that any thing configured for real-time replication (such as SSL or NAT) would be respected as that real-time channel would be re-used.

However, real-time replication expects that both clusters be the same ring-size.  So this would impact the ability for this to be used as part of a cluster migration strategy.  

For now, I'm proceeding with a single HTTP client for PUTing as-is to repair.  This acts as a natural brake on the throughput of repair - but it does mean that everything will work when the two clusters are different ring sizes.

**Comment by martinsumner** [comment]
The correct long-term answer is to use rabl (or an equivalent real-time replication method that doesn't have the ring-size limitations.

However, there are now some issues making rabl available for a 2.9 release, in that support for OTP R16 is not available on any supported rabbit deployment (all supported versions would require Riak 3.0).

**Comment by russelldb** [comment]
The rabbit beam and riak beam don't have to be the same, do they?

**Comment by martinsumner** [comment]
@russelldb - good point.  This was just a problem in my head, now you mention it, there is no reason I can think of why they need to be the same version.

**Comment by martinsumner** [comment]
First test for this - https://github.com/nhs-riak/riak_test/blob/mas-i1691-ttaaefullsync/tests/repl_ttaaefs_manual.erl.

The test exposed the limitation of using the HTTP API, in that keys must be UTF-8 format.  For example if you add a key of the form <<129:32/integer>>, then the HTTP API will fail to list_keys or nay other operation that tries to JSON format the output.  So it will be better to add a PB interface to aae_fold and use PB for this.

**Comment by martinsumner** [comment]
There's some work to be done here:

Tombstones need further thought;
Options in addition to asis requires (don't update lmd, disable hooks);
Different object types may need different handling.

I think it would be good if the source notified the sink of the keys which needed updating, and left the sink to work out how to request those objects.  This would help make a solution to be used by Riak -> Other replication as well as Riak -> Riak.  Perhaps have a "raw_get" API to allow for objects to be fetched without translation for Riak -> Riak.

**Comment by martinsumner** [comment]
The attempt to write this using the existing external API for GET/PUT (and hence have a simple AAE full-sync not dependent on any real-time replication) has hit issues with:

- No mechanism for doing a delete `asis`
- Issues with passing through and preserving `last_modified_date`

Need to make a decision to either:

- Get it working with existing real-time replication;
- Get it working with an alternate real-time replication (not tied to matching ring_size between clusters) e.g. rabl, or equivalent;
- Get it working by extending the http/pb api to add all the required changes to push objects unmodified;
- Get it working by extending the http/pb api to allow an encoded object to be pushed (i.e. normal http header semantics are ignored, and there is an option to send an object over the interface in the repl wire format).

I have doubts about option 3 - in that I suspect it may hit further issues as the replication of different datatypes are explored.  However, part of the long-term ambition is to make it easier to replicate from Riak out to different stores, tying back the replication to implementation to the internal riak_object format isn't ideal in this regards - and the other options are all pushing away from achieving this.

**Comment by martinsumner** [comment]
When fetching a tombstone the riak_kv_get_fsm will return only `{error, {deleted, Vclock}}` and no further information about the tombstone.  There is a last-modified-date on the HTTP response, this appears to be the date/time of the request and is not related to the modified time of the object  (e.g. the PUT time of the tombstone).

More information than the vector clock is needed to correctly replicate a tombstone, at least a last modified date is required as well (otherwise modified since type queries won't work as expected - causing false negative results in such queries).

Last modified dates are updated by the riak_kv_put_fsm (note that deletes are just empty objects that go through this path - so they should also get a last modified date).

https://github.com/basho/riak_kv/blob/develop-2.9/src/riak_kv_put_fsm.erl#L390

This is dependent on the option `update_last_modified`.  The current repl code sets the `update_last_modified` to false to prevent this changing on replication. 

In a delete, the `riak_kv_delete` creates an empty object (with empty metadata) to pass to the `riak_kv_put_fsm`, so generating a new delete will lead to a tombstone with a new last_modified_date.  

The current riak_repl code replicates the tombstone object (including the metadata), and starts a `riak_kv_put_fsm` to PUT the tombstone (and triggers reaping):

https://github.com/basho/riak_repl/blob/develop-2.9/src/riak_repl_util.erl#L146-L172

**Comment by martinsumner** [comment]
The branch https://github.com/martinsumner/riak_kv/compare/develop-2.9...martinsumner:mas-i1691-ttaaefullsync now has a rudimentary repl solution to complement the AAE full-sync.

The test https://github.com/nhs-riak/riak_test/blob/mas-i1691-ttaaefullsync/tests/repl_ttaaefs_manual.erl will now pass.

There is a lot of work still required to hook this together and automate the behaviour, but hopefully this should fall into place the next week.  The new repl solution takes some of the discoveries from the rabl work on effective topologies, and tries to create an efficient mechanism whereby references to objects rather than whole objects can be queued (making easier to support bigger queues).  It uses the riak_core_priority_queue module (which is derived in part from rabbitmq) rather than rabbitmq as a whole separate product (although rabbitmq could be substituted).

Target is to write up the new approach and the rational behind it by the end of the month.

**Comment by martinsumner** [comment]
Second test now working, which allows the replication triggered by full-sync to happen semi-automatically by using the first working parts of a new real-time repl solution.

https://github.com/nhs-riak/riak_test/blob/mas-i1691-ttaaefullsync/tests/repl_ttaaefs_semiauto.erl

All code still in https://github.com/martinsumner/riak_kv/compare/develop-2.9...martinsumner:mas-i1691-ttaaefullsync

**Comment by martinsumner** [comment]
Changes required to ttaaefs_manager following review with @ThomasArts:

- Tuple-length of the handle_cast for the no_sync message - with riak_test to confirm no crash.
- Check the 'pause' status within handle_info work_item.
- Review consistency of triggering loop timeout when making dynamic configuration changes (why timeout on set_sink but not set_queuename?).

Major change is to review the start tie of the loop.  Should start time of the loop always be the last midnight passed?  This way if we have a staggered start of a cluster the schedules will all align (so that the offsets are effective in splitting the start points of the work).

Should the system be moved from depending on timeouts, but to be running off a single heartbeat (i.e. where a heartbeat is prompted each time by the handle_info timeout receipt).

**Comment by martinsumner** [comment]
Changes required to replrtq_snk following review with @ThomasArts.

Concurrency of workers needs to account for deferred work items (which otherwise look like busy workers).

**Comment by martinsumner** [comment]
Changes required to riak_test tests following review with @ThomasArts.

nextgenrepl_aaefold

L126-L128 wait_for_outcome before checking all others are errors

L150 repl range before as well

nextgenrepl_rtq_auto - spawn processes to modify different key ranges on different clusters


Test required with siblings:
 - setup clusters
 - replicate an object
 - break real
 - update object on both sides of partition
 - heal partition
 - confirm everything consolidates without spurious additional replication loops


Chained replication test:
 - real-time repl does not A -> B -> C
 - full-sync repl does A -> B -> C

Equivalent of nextgenrepl_ttaaefs_autoall.erl for per-bucket replication

**Comment by martinsumner** [comment]
When testing the implementation, things work as expected with the repl_cache enabled, but there is an intermittent issue without the repl_cache.

When repl_cache is not enabled, as the coordinator does not have the result cached, a reference to the object (not the object and the coordinator) is passed to the queue to for replication.  If this is the next item on the queue this may be picked up immediately by a request from the other site, and a get_fsm will then be launched to fetch the object.

However, at this stage the object may only be on 1 vnode, and so a response may be formed from n - 1 vnodes (not including the one with the old object).  Consequently an old version of the object may be replicated.

So real-time replication will essentially forget to replicate that change.  This will then be fixed by a future AAE full-sync exchange.  Under volume testing this occurs in less than 0.01% of requests.  In a small-object riak_test (unrealistic devrel setup) about 0.1% of requests

There are some possible courses of action here:

1. Enforce the use of the repl_cache (or heavily caveat the failure to use the repl_cache), when replication is to be enabled

2. Change the get_fsm to wait for either n responses, or the expected vector clock in this case (i.e. the 'r' val of the GET becomes flexible, it is satisfied by either n responses, or as soon as the expected vector clock is seen)

Option 2 seems like a more correct answer.  However, changes to the behaviour of the get_fsm carry a higher degree of risk.

Further investigation into the potential to implement Option 2 indicates it might not be too risky a change.  It looks simple to update the get_core enough/response functions to account for whether an expected clock has been received (and fallback to r=n if not).

**Comment by martinsumner** [comment]
Commit for option 2 fix:

https://github.com/martinsumner/riak_kv/commit/a4aa1ae5bf3c485e50f3f9c955e39821dd3f4aeb

**Comment by martinsumner** [comment]
<img width="1596" alt="Comparison - 291 and 290 repl and fullsync" src="https://user-images.githubusercontent.com/1628897/60575742-fe043800-9d73-11e9-93f3-4c5cbd1d0d20.png">

Chart shows difference in throughput between using 2.9.0 with riak_repl (real-time and keylist full-sync with minimised concurrency), vs using the proposed 2.9.1 repl solution (real-time, with a complete bi-directional) AAE full-sync every fifteen minutes.  The 2.9.1 test achieves 3.7% more throughput during the test.

In the 2.9.0 test the full-sync does not complete.  In the 2.9.1 test each full-sync completed in < 10s.

The test was for 2 x 4-node cluster using standard NHS mixed load basho_bench script.  All bench requests were directed at a single cluster.

**Comment by martinsumner** [comment]
Some tests still do:

- Comparison using more default settings (with more concurrency) on the riak_repl full-sync (ideally so a  full-sync is actually completing during the test);
- Comparison with non-leveled backends;
- Comparison on more realistic cluster size;
- Comparison with the nextgenrepl repl_cache disabled.

**Comment by martinsumner** [comment]
https://github.com/basho/riak_kv/blob/riak_kv-2.9.1/docs/NextGenREPL.md
