### ISSUE TITLE
Unhandled false return from riak_index:object_key_in_range

### ISSUE THREAD

**Issue by pma** [basho/riak_kv#1758]
This case statement https://github.com/basho/riak_kv/blob/develop-2.9/src/riak_kv_leveled_backend.erl#L405 should handle a possible return of 'false' from riak_index:object_key_in_range, due to this line here: 
https://github.com/basho/riak_kv/blob/develop-2.9/src/riak_index.erl#L469

I got the pattern match error while playing with RiakCS using leveled as backend. Listing directories via the s3 API would trigger the error under some situations I couldn't  reproduce reliably.

**Comment by martinsumner** [comment]
Any clues at all about the conditions?  It will help me generate a riak_test test.

I can match the riak_kv_eleveldb_backend code to resolve this I assume - https://github.com/basho/riak_kv/blob/develop-2.9/src/riak_kv_eleveldb_backend.erl#L854-L855

**Comment by pma** [comment]
@martinsumner I still have to figure out how RiakCS  maps paths to keys to come up with a test case that does not depend on running RiakCS. This was the simpler case to reproduce via the S3 API:

**When using leveldb backend**
```
~ ❯❯❯ s3cmd mb s3://mybucket                                                                                                                                                                                    ⏎
Bucket 's3://mybucket/' created
~ ❯❯❯ s3cmd put test.txt s3://mybucket/foo/bar/baz/test.txt                                                                                                                                                     ⏎
upload: 'test.txt' -> 's3://mybucket/foo/bar/baz/test.txt'  [1 of 1]
 4 of 4   100% in    0s    85.65 B/s  done
~ ❯❯❯ s3cmd put test.txt s3://mybucket/
upload: 'test.txt' -> 's3://mybucket/test.txt'  [1 of 1]
 4 of 4   100% in    0s    91.32 B/s  done
~ ❯❯❯ s3cmd ls s3://mybucket/foo/
                       DIR   s3://mybucket/foo/bar/
```

**When using leveled backend**
```
~ ❯❯❯ s3cmd mb s3://mybucket                                                                                                                                                                                    ⏎
Bucket 's3://mybucket/' created
~ ❯❯❯ s3cmd put test.txt s3://mybucket/foo/bar/baz/test.txt
upload: 'test.txt' -> 's3://mybucket/foo/bar/baz/test.txt'  [1 of 1]
 4 of 4   100% in    0s    78.07 B/s  done
~ ❯❯❯ s3cmd put test.txt s3://mybucket/
upload: 'test.txt' -> 's3://mybucket/test.txt'  [1 of 1]
 4 of 4   100% in    0s    97.81 B/s  done
~ ❯❯❯ s3cmd ls s3://mybucket/foo/
connection without response)
WARNING: Waiting 3 sec...
^CSee ya!
```

The 'ls' crashed Riak with the error:
```
root@riak-kv:/# cat /var/log/riak/error.log
2020-06-08 13:08:10.104 [error] <0.1474.0> gen_server <0.1474.0> terminated with reason: no case clause matching false in riak_kv_leveled_backend:'-fold_objects/4-fun-0-'/9 line 405
2020-06-08 13:08:10.104 [error] <0.1474.0> CRASH REPORT Process <0.1474.0> with 0 neighbours exited with reason: no case clause matching false in riak_kv_leveled_backend:'-fold_objects/4-fun-0-'/9 line 405 in gen_server:terminate/6 line 744
2020-06-08 13:08:10.105 [error] <0.1467.0> Supervisor {<0.1467.0>,poolboy_sup} had child riak_core_vnode_worker started with {riak_core_vnode_worker,start_link,undefined} at <0.1474.0> exit with reason no case clause matching false in riak_kv_leveled_backend:'-fold_objects/4-fun-0-'/9 line 405 in context child_terminated
```

When 'riak_index:object_key_in_range/3' returns false, the leveldb backend halts the folding and returns the last accumulator.

Next I'll look into the 'ls' implementation of RiakCS to come up with a reproducible test case directly on riak-kv.

**Comment by martinsumner** [comment]
There already is a riak_test for this as it happens:

https://github.com/basho/riak_test/blob/develop-2.9/tests/verify_cs_bucket.erl

And it passes on eleveldb, and fails on leveled with the failure you detect.

This test was never included in the kv release set, so I hadn't noticed it before.

I will confirm the fix today, and add the test in for the future.

**Comment by martinsumner** [comment]
The problem is also related to the fact that we don't handle the start_key correctly in query, and so  we're always scanning the whole bucket.  Should have a fix tested this weekend.

**Comment by martinsumner** [comment]
I've extended he test to make sure it covers all start/end inclusive/exclusive scenarios:

https://github.com/basho/riak_test/pull/1347

Test now included in standard test suite to be run for each release
