### ISSUE TITLE
Tictac AAE rebuild and unexpected repairs

### ISSUE THREAD

**Issue by martinsumner** [basho/riak_kv#1771]
When running tictac aae in parallel mode it is necessary to run infrequent but regular rebuilds - whereby the AAE store is rebuilt from the vnode store, and then the AAE tree is rebuilt from the newly built AAE store.

A strange problem is re-occurring in a stress test.  The stress test is intended to push a cluster by rebuilding all stores at once (which would occur if tictac AAE was enabled in parallel mode for the first time).  The test is run on a 8-node cluster.

Test process:

1. Load data (about 1bn objects) split between domainRecordT0 and domainDocumentT0 buckets (keys in different buckets have different types of values, but buckets themselves have same properties), with anti-entropy enable, but tictacaae disabled.

2. Restart all nodes with tictacaae enabled, and anti-entropy disabled.

3. After restart start fresh load of data split between buckets domainRecordT1 and domainDocumentT1.

4. Confirm all stores build, all trees build and there are no errors.

5. Restart all nodes again, after deleting the tictac stores.

6. After restart start fresh load of data split between buckets domainRecordT2 and domainDocumentT2.

7. Confirm all stores build, all trees build and there are no errors.

At this stage there is a strange issue.  The stores and trees rebuild, but once a pair of partitions in a preflist both have trees rebuilt, we begin to see key_deltas being discovered - where one vnode has a bunch of keys, and the other doesn't.

The intriguing thing, is that almost all (>> 99%) the keys which have deltas are in bucket domainRecordT1 - there ar eno deltas discovered in domainDocumentT1 (or any other buckets).

8. Restart all nodes again, after deleting the tictac stores.  This time don't do a data load.

9. Confirm all stores build, all trees build and there are no errors.

Interestingly we don't see the key_deltas now.

10. Restart all nodes again, after deleting the tictac stores.

11. After restart start fresh load of data split between buckets domainRecordT3 and domainDocumentT3.

12. Confirm all stores build, all trees build and there are no errors.

Again the strange issue re-occurs.  This time almost all the key deltas are in domainRecordT2, with a small amount (<1%) in domainRecordT1.

Some observations:

A. The key deltas are all keys loaded during the previous rebuild period (observing the timestamp in the vector clock).

B. There are read repairs occurring in the cluster, but most key deltas don't result in read repairs (the count of read repairs is much less than the total delta key count).  So most of the deltas discovered do not reflect a genuine delta between the vnode stores, but are a delta between the newly built key stores.

C. The loading of the data during the test run, starts before the rebuild is triggered.  So when the test is started the domainRecordT{N} bucket with which we will have the problem is alphabetically the highest bucket in the store, but by the time the rebuild is triggered there will already be some domainRecordT{N+1} entries.

D. The "deltas" discovered represent a minority of the objects loaded into that bucket (<1%) but still a large number (>100K).

This is just so weird.  I've not yet managed to recreate in a smaller setup, and each cycle (e.g. step 10-12) takes about 24 hours, so experimenting to try and tie this down is hard to do.

Currently this is occurring in the planned 2.9.6 release.  I've not bene able to confirm if it occurs in current releases - I don't know if it is introduced by 2.9.6 changes.

**Comment by martinsumner** [comment]
On loading, there is a counter kept of object specs loaded into the tictac aae keystore.  The final load count varies between vnodes - from 56.6M to 57.2M -  a difference of about 600K.

The issues of deltas appears to be concentrated on those with the lower load counts.

Each AAE partition should exchange with 4 other partitions (2 up the ring, 2 down).  Looking at a node in the test - those AAE controllers that reached 57.2M are exchanging without deltas to at least 3 out of 4, but those that only reached 56.8M are generating deltas when exchanging with all 4 paired partitions.

**Comment by martinsumner** [comment]
when the issue occurs, there are logs of the count of leaves in which deltas are discovered.  By default, the counts are throttled to 256.

This means that if the root (4096 branches) is entirely divergent, then just 256 branches will be checked.  If the leaves are entirely divergent then it should discover 65536 deltas.  However in the test there are much lower numbers of deltas, but the delta counts seem to form a pattern associated with multiples of 1560 delta leaves (from 256 delta branches).

<img width="1616" alt="Test6_BranchBands" src="https://user-images.githubusercontent.com/1628897/89897378-d5857900-dbd6-11ea-84bf-15dae0b1b3c7.png">

<img width="1619" alt="Test7_BranchBands" src="https://user-images.githubusercontent.com/1628897/89897312-b981d780-dbd6-11ea-98fa-8d7463bc769c.png">

In this case 1560 divergent branches correlates to 25,000 (`4096 * 1560 / 256`) keys being broken for a preflist (which would mean a delta of 75,000 keys in the keystore (as N=3, and assuming loss is independent of preflist)

**Comment by martinsumner** [comment]
Adding this extra logging to count in the fold https://github.com/martinsumner/kv_index_tictactree/commit/7f672c2ef9649686614edc7d74545aa5a8fee374 reveals that all keys seen by the folds are sent to the aae_keystore, and received by the aae_keystore.  So the missing keys are not being seen by the fold i.e. the problem almost certainly lies within eleveldb.

**Comment by hanssv** [comment]
Good thing we didn't start a massive testing effort on aee_keystore/controller 😄

**Comment by martinsumner** [comment]
The basho leveldb database has an option called `paranoid_checks` - https://github.com/basho/leveldb/search?q=paranoid&unscoped_q=paranoid.

By default this is disabled, which in essence says continue in the face of corruption.  Perhaps this might also mean continue in the face of failure to open files due to contention, or some other temporary issues which look like corruption.

But ultimately, the default position of leveldb in riak in a choice between incomplete data and crashing - is to choose incomplete data.  So the behaviour of leveldb in this case (if it is skipping chunks of data from a fold when under extreme pressure), would be in line with that general principle.

**Comment by martinsumner** [comment]
Ultimately it is safe for an individual node to temporarily lose data because of all the other mechanisms in a N >1 store to handle that (and recover if the loss is permanent).  This issue is one from which the database ultimately recovers (albeit potentially after 24h + of AAE rehashing).
