### ISSUE TITLE
Question about Riak KV latest version

### ISSUE THREAD

**Issue by sachdeva-vivek** [basho/riak_kv#1787]
Hi, 

It's not really an issue but wanted to know the difference between releases on GitHub tags vs https://docs.riak.com/riak/latest/downloads/.

Under Github, the latest release shows Riak KV 3.0.4 - Release and on https://docs.riak.com/riak/latest/downloads/, the latest release is Riak KV 2.2.3. Which one should I use for my production environment?

Thanks in advance,
Vivek

**Comment by martinsumner** [comment]
The docs.riak.com website is out of date.  The latest version is Riak KV 3.0.4, and this is the best choice for a new production environment.

Packages available at https://files.tiot.jp/riak/kv/3.0/

**Comment by sachdeva-vivek** [comment]
Thanks a lot @martinsumner!
