### ISSUE TITLE
We still expose "riak" with a custom setting for an access URL

### ISSUE THREAD

**Issue by ghost** [basho/riak_kv#304]
This code in question adds "riak": even if we have a custom "raw_name": 

[riak_kv_web.erl]

raw_dispatch() ->
    case app_helper:get_env(riak_kv, raw_name) of
        undefined -> raw_dispatch("riak");
        Name -> lists:append(raw_dispatch(Name), raw_dispatch("riak"))
    end.

**Comment by evanmcc** [comment]
This seems intentional; the old API is presumably going away at some point, which will obsolete this issue.  Closing since it's unlikely to be fixed before then.
