### ISSUE TITLE
Provide a more user-friendly CLI

### ISSUE THREAD

**Issue by seancribbs** [basho/riak_kv#308]
Moved from https://issues.basho.com/show_bug.cgi?id=984, reported by @jpartogi

Currently we need to use the erlang client to interface to riak from command line. But however this is not really user friendly and most of the time enforce the user to understand erlang. Because of this sometimes we need to open the manual.

For example (taking redis CLI as an example): This:

``` text
del "groceries" "mine"
```

is much more user friendly and productive than this:

``` erlang
riakc_pb_socket:delete(Pid, <<"groceries">>, <<"mine">>).
```

**Comment by evanmcc** [comment]
If there isn't anyone actively working on it, I think that we should close it until there is.  In the mean time, maybe [Contact](https://github.com/metadave/contact) might be something for interested users to explore?
