### ISSUE TITLE
Add request stages timing to get FSM

### ISSUE THREAD

**Issue by jonmeredith** [basho/riak_kv#309]
Add equivalent functionality to the get FSM to track the request stages like the put FSM is able to do.

(dev1@127.0.0.1)2> C:put(riak_object:new(<<"b">>,<<"k">>,<<"v">>),[details]).
{ok,[{response_usecs,113057},
     {stages,[{prepare,45894},
              {validate,12677},
              {precommit,6448},
              {execute_local,64},
              {waiting_local_vnode,14082},
              {execute_remote,47},
              {waiting_remote_vnode,33845}]}]}

It may even be valuable to try and break down wait time by vnode.

**Comment by engelsanchez** [comment]
@jonmeredith I see we have some or all of what you wanted now? (below) Is there anything to add or can we close this issue?

element(3, C:get(<<"b">>, <<"k">>, [details])).
[{vnode_oks,2},
 {response_usecs,1088},
 {stages,[{execute,211},
          {prepare,258},
          {validate,38},
          {waiting_vnode_r,581}]}]

**Comment by evanmcc** [comment]
Looks to be fixed to me, closing.  Please yell if you think that some specific enhancement remains to be done.
