### ISSUE TITLE
Deleted keys stay in index queries indefinitely

### ISSUE THREAD

**Issue by sfescape** [basho/riak_kv#330]
Deleted keys remain in indexes indefinitely if the tombstone reap process fails. The key will finally be removed once a GET request is made on the key.

**Comment by PharkMillups** [comment]
For a thorough discussion of this issue, see [this thread](http://lists.basho.com/pipermail/riak-users_lists.basho.com/2012-May/008431.html) on the Riak Mailing list.

**Comment by sfescape** [comment]
As predicted in the thread, changing my delete changed the behavior. Deleting 80K keys resulted in no residual keys in the index. Here is the change I made to the delete:

this.bucket.delete(key)
      .pw(Quora.ALL)
      .pr(Quora.ALL)
      .w(Quora.ALL)
      .r(Quora.ALL)
      .execute();

**Comment by evanmcc** [comment]
This is a dupe of issue #311.
