### ISSUE TITLE
Some useful REST API features should be implemented on PBC API

### ISSUE THREAD

**Issue by taichi** [basho/riak_kv#337]
I believe all users who needs more performance would like to process all operations via PBC API. 
However, user cannot do so due to lack of some APIs.
- Backet Properrties of PBC API should have more fields 
  PBC API is strictly limited to access to Backet Properties. 
  That is, we have to use REST API for Backet management.  
  Some applications creates per-user Backets. 
  This indicates that we can write much simpler and faster application by creating/deleting a large amount of Backets.  
- PBC API should support Link Walking 
  It would be great if we could use Link Walking, which is really useful feature.
- PBC API RpbGetServerInfoResp should return the same information to REST API /stats 
  RpbGetServerInfoResp returns so poor information that we can't use this API at all. 
  /stats includes many useful information which is required for client to coordinate with Riak. 
  PBC API user who wants fast client needs this information.

**Comment by evanmcc** [comment]
HTTP and PBC APIs should be at parity.
