### ISSUE TITLE
Spurious 400 after HTTP MapReduce

### ISSUE THREAD

**Issue by beerriot** [basho/riak_kv#338]
History:
- https://issues.basho.com/show_bug.cgi?id=1222
- https://issues.basho.com/show_bug.cgi?id=1324

The `riak_kv_wm_mapred` module, which provided the MapReduce HTTP interface, implements its timeout mechanism by scheduling a message to be delivered to its process after the timeout has occurred:

https://github.com/basho/riak_kv/blob/master/src/riak_kv_wm_mapred.erl#L148

When a MapReduce query finishes before that message is received, however, mochiweb is likely to receive it instead:

https://github.com/mochi/mochiweb/blob/master/src/mochiweb_http.erl#L69-70

The `mochiweb_http` module expects _only_ tcp socket messages, so if this unknown `pipe_timeout` message is received, mochiweb immediately sends a 400 error message to the client.  The message is safe to ignore, but it can be confusing to prove that it came from this bit of code, and not somewhere else.

What `riak_kv_wm_mapred` should do instead is keep the timer reference around, and cancel the timer before returning control to mochiweb.  Alternatively, all pipe and timeout messages should be handled by a process other than the mochiweb/webmachine/socket-holding process, which would also make it possible to remove the use of the `mochiweb_request_force_close` hack:

https://github.com/basho/riak_kv/blob/master/src/riak_kv_wm_mapred.erl#L299-300

**Comment by joecaswell** [comment]
See also http://help.basho.com/tickets/1423
