### ISSUE TITLE
transfer status - percentage complete

### ISSUE THREAD

**Issue by rzezeski** [basho/riak_kv#356]
This is in reference to the `riak-admin transfers` command and written in response to Matt Ranney's comment on a [recent blog post](http://basho.com/blog/technical/2012/06/25/Riak-Admin-Transfers-in-1-2-Release/).

**IFF** the information is easy to obtain then it would be very helpful to display the percentage complete for each transfer.

**Comment by evanmcc** [comment]
This has been addressed for backends that support it.

**Comment by jrwest** [comment]
addressed in https://github.com/basho/riak_core/pull/290 and https://github.com/basho/riak_kv/pull/526
