### ISSUE TITLE
JS Built-Ins don't handle tombstones

### ISSUE THREAD

**Issue by beerriot** [basho/riak_kv#358]
Migrating issue from Buzilla. See the [original thread](https://issues.basho.com/show_bug.cgi?id=1269) for existing comments and code. 

(Moving here from https://github.com/basho/riak_pipe/issues/47, because it's a KV issue.)

**Comment by beerriot** [comment]
This was re-reported as https://github.com/basho/riak/issues/190

**Comment by darrel343** [comment]
Also running into this issue. It's causing <<\"SyntaxError: syntax error\">>},{<<\"source\">>,<<\"()\">> after a delete.

Is there a workaround for this, or a rule-of-thumb, for how long I should have to wait until I can query for the new data I've added to the relevant buckets?

**Comment by laurilehmijoki** [comment]
I also did run into this problem. Any tips on how to work around it?

**Comment by laurilehmijoki** [comment]
One workaround is to use LevelDb instead of Bitcask.

**Comment by evanmcc** [comment]
That won't work, level has tombstones as well. Check the metadata for
X-Riak-Deleted, and discard (return []) if it is set.

**Comment by rogier** [comment]
As a workaround I used the following in my javascript map-reduce:
`function(riakObject) {
     if (riakObject.values[0].metadata['X-Riak-Deleted'] == 'true') return []
     var data = Riak.mapValuesJson(riakObject)[0];
     if (...) return [riakObject.key];
     else return [];
    }`

**Comment by mde** [comment]
@rogier Thank you for this workaround. I can't believe this is still broken.

**Comment by charl** [comment]
@rogier if I try your workaround I get the following:

```
# curl -v -XPOST http://192.168.0.8:8098/mapred?chunked=true -H 'Content-Type: application/json'  -d '{"inputs":"tweets", "query":[{"map":{"language":"javascript", "source":"function(riakObject) {if (riakObject.values[0].metadata['X-Riak-Deleted'] == 'true') return []; var data = Riak.mapValuesJson(riakObject)[0]; if (data) return [riakObject.key]; else return [];}", "keep":true}}]}'
* About to connect() to 192.168.0.8 port 8098 (#0)
*   Trying 192.168.0.8... connected
> POST /mapred?chunked=true HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: 192.168.0.8:8098
> Accept: */*
> Content-Type: application/json
> Content-Length: 279
> 
* upload completely sent off: 279out of 279 bytes
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
< Date: Mon, 09 Sep 2013 08:52:58 GMT
< Content-Type: multipart/mixed;boundary=7vtd8LIRjuzbSk64gGcBKGupuij
< 
* Connection #0 to host 192.168.0.8 left intact
* Closing connection #0
{"lineno":1,"message":"ReferenceError: X is not defined","source":"unknown"}
```

**Comment by alexmoore** [comment]
@charl That's because you didn't escape the quotes around `X-Riak-Deleted`.  This version should work:

``` bash
curl -XPOST http://192.168.0.8:8098/mapred -H 'Content-Type: application/json' \
    -d '{"inputs":"tweets", "query":[ {"map":{"language":"javascript", 
            "source":"function(riakObject, keyData, arg) { 
                if(riakObject.values[0].metadata[\"X-Riak-Deleted\"]){ return []; } 
                else { return Riak.mapValuesJson(riakObject)[0]; }}",
            "keep":true}}]}'
```

**Comment by charl** [comment]
@alexmoore thanks for the feedback.

Unfortunately I no longer use riak.

**Comment by ayushmishra2005** [comment]
Did anybody find the solution of the issue? Issue is still open. I have got stuck badly in this issue. Now I am deciding to replace riak with any other DB.

Can anyone help me to resolve this? Thanks in advance.

**Comment by mde** [comment]
@rogier's workaround above worked fine for me.

**Comment by ayushmishra2005** [comment]
This is a hack not a solution.

**Comment by seancribbs** [comment]
@ayushmishra2005 We appreciate your frustration with this broken feature. Unfortunately, we have deprecated JavaScript MapReduce with the Riak 2.0 release and are currently designing a long-term replacement. In the meantime, please use Erlang for phase functions. 

You may use some of the Erlang built-ins to accomplish close to what you want, as I will outline below.

If you want to skip tombstones altogether, pass the `"filter_notfound"` arg:

``` javascript
{"map":{"language":"erlang", 
        "module":"riak_kv_mapreduce", 
        "function":"map_object_value_list", 
        "arg":"filter_notfound"}}
```

If you prefer to return something else when encountering a tombstone, do so like this, replacing `"missing_marker"` with the value you want to substitute:

``` javascript
{"map":{"language":"erlang",
        "module":"riak_kv_mapreduce",
        "function":"map_object_value_list",
        "arg":{"sub":"missing_marker"}}}
```

Note that this built-in will not parse the JSON inside the value, you might want to do that in a subsequent phase or write your own map function to do so.
