### ISSUE TITLE
HTTP API can return very long Link header when listing keys/buckets

### ISSUE THREAD

**Issue by jerith** [basho/riak_kv#362]
`GET /buckets/bucket/keys?keys=true` and `GET /buckets?buckets=true` return Link headers for each item returned. This can result in a very long header when listing a large number of items, which makes certain HTTP clients (such as txriak) very unhappy.

**Comment by jerith** [comment]
When listing keys, one can use `keys=stream` to get a chunked response, which excludes the Link headers. Perhaps a similar streaming API for buckets would be a good idea?

**Comment by seancribbs** [comment]
Addressed by #491
