### ISSUE TITLE
Eliminate use of zlib:zip() and zlib:unzip()

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_kv#391]
In a many-core environment, use of the zlib:zip() and zlib:unzip() function isn't a good idea.  Each appears to open an close an Erlang port (for the "zlib_drv" driver) for each invocation.  Inside the R15B01 virtual machine, all allocations of a new port # are serialized by the 'get_free_port' mutex.

Suggestion: eliminate zlib's use in favor of term_to_binary(VClock, [compressed]).  Or _something_ else that doesn't allocate & free an Erlang port on each call.

NOTE: zlib:zip() and unzip() are also used to compress handoff payload.  On extremely busy systems (e.g. 8K Riak ops/sec/node or more), this same port allocation serialization probably interferes quite a bit with handoff.

**Comment by evanmcc** [comment]
This issue is addressed in handoff land and there is some code for it in the vclock machinery that is off by default.

**Comment by jtuple** [comment]
We should test the new behavior during 2.0 testing cycle and switch the defaults to use the non-zlib approach in 2.0. Or, if testing is inconclusive, re-assign this issue to 2.1

**Comment by evanmcc** [comment]
this is already in place. this is guarded by a capability, so there isn't a setting to change.  verified via redbug.

```
19:19:37 <0.5130.0>({riak_core_vnode,init,1}) erlang:binary_to_term/1 -> 
      {encode_raw, {<<"b1">>, <<120,198, 31,0>>, <<53,1,0,0,0,34, ...>>}} 
```
