### ISSUE TITLE
HTTP mapred yields 500 on missing Content-Type header

### ISSUE THREAD

**Issue by krestenkrab** [basho/riak_kv#396]
The `known_content_type` WM callback crashes if no content-type is given.

The error happens around these lines: https://github.com/basho/riak_kv/blob/master/src/riak_kv_wm_mapred.erl#L98 because the call to `wrq:get_req_header("content-type", RD)` returns `undefined`, and then soon thereafter there is a no-match inside `base_ctype`.

**Comment by krestenkrab** [comment]
This mail http://lists.basho.com/pipermail/riak-users_lists.basho.com/2012-September/009490.html is the original error report by Colin Alston

**Comment by seancribbs** [comment]
It should obviously check for the presence of the Content-Type header before trying to parse it. Maybe this would work?

``` erlang
ctype_ok(RD) ->
    wrq:get_req_header("content-type", RD) =/= undefined andalso valid_ctype(get_base_ctype(RD)).
```

**Comment by evanmcc** [comment]
This appears to have been fixed.
