### ISSUE TITLE
mapred on key-range should be faster for leveldb

### ISSUE THREAD

**Issue by krestenkrab** [basho/riak_kv#397]
Since some backends provides efficient range fold (in particular eleveldb and hanoidb), we should add an API that provides fast M/R for objects in a given key range.

Right now, this is done by first getting the keys in a given range (which is actually reasonably fast in eleveldb and hanoidb), and then getting each object individually.

Since leveldb and hanoi actually has the objects stored close to each other, it would be _much_ faster to simply provide all the values in a given key range to a reduce phase.

Much faster. Grr.. :-)

**Comment by evanmcc** [comment]
This would indeed be a good idea, but currently this isn't on our roadmap.  I've marked this bug as a feature request, but since we don't plan on doing this in the next 2 or 3 releases, I am going to close it.

Thanks for the suggestion!
