### ISSUE TITLE
system_info(global_heaps_size) not supported in R15B02

### ISSUE THREAD

**Issue by vinoski** [basho/riak_kv#411]
The `riak_kv_stat:system_stats/0` function calls `erlang:system_info(global_heaps_size)` but that call results in a `badarg` exception under Erlang R15B02. The OTP team removed support for `global_heaps_size` in [commit 9cfeeb9b](https://github.com/erlang/otp/commit/9cfeeb9b7e66a3345cbc0e5b4b634cb5965635fc) in the erlang/otp repo.

**Comment by russelldb** [comment]
Got it, will remove/substitute in a backwards compatible way for 1.3. Thanks.

**Comment by russelldb** [comment]
See https://github.com/basho/riak_kv/pull/415 for proposed fix. Welcome review / comments.

**Comment by russelldb** [comment]
Fixed with https://github.com/basho/riak_kv/pull/415
