### ISSUE TITLE
Moar stats for riak

### ISSUE THREAD

**Issue by russelldb** [basho/riak_kv#412]
Add the following from https://github.com/basho/cabal/issues/15 for 1.3 release:

```
PUT FSM timings
GET FSM timings
Per Vnode request operation and duration
Read Repair Stats (count, sent to dest node, repair reason, dest type (fallback/primary)
Riak_api pb_connects / pb_active should use supervisor:count_children() since a crashing connection will not call the terminate fun so active does not shrink appropriately.
```

**Comment by jonmeredith** [comment]
Go @russelldb !

**Comment by russelldb** [comment]
First PR, just adds timing to FSMs and sticks them in folsom
https://github.com/basho/riak_kv/pull/414

**Comment by russelldb** [comment]
Second PR https://github.com/basho/riak_kv/pull/417 adds dimensions to `read_repair` stats.

**Comment by russelldb** [comment]
~~Third PR, for `pbc_active` bug https://github.com/basho/riak_api/pull/17~~

Done, thanks Sean!

**Comment by russelldb** [comment]
Fouth PR, for vnode get/put times and per index https://github.com/basho/riak_kv/pull/418

**Comment by russelldb** [comment]
Another three. Oh my, sorry.

https://github.com/basho/riak_core/pull/252
https://github.com/basho/riak_api/pull/18
https://github.com/basho/riak_kv/pull/428

**Comment by russelldb** [comment]
Added the bare minimum to pipe ~~https://github.com/basho/riak_pipe/pull/60~~ This has been reviewed., and is ready to merge when the next are in.

**Comment by russelldb** [comment]
Some level db stats for MvM https://github.com/basho/riak_kv/pull/431

**Comment by slfritchie** [comment]
A friendly note to all participants ... today is code freeze day.

**Comment by russelldb** [comment]
Merged, many thanks for the most patient and diligent review.
