### ISSUE TITLE
stats should not fail

### ISSUE THREAD

**Issue by evanmcc** [basho/riak_kv#441]
It'd be nice if we tracked down all of the lingering timeouts that can potentially cause a stats call to fail.  We often error out with a 500 with all of our stats contained in the body of it.  It would be better if some stats cannot be fetched in a timely manner that we just drop or say 'couldn't fetch' for those stats, instead of failing the entire call.  Partial information is better than none, and this sounds easier than teaching monitoring solutions to parse our error messages for whatever data they may contain.

**Comment by russelldb** [comment]
Can I have some examples, please? How often is often?

I think I have an answer to this, anyway. 1.3 includes a finer grained per-metric calculation and cache model, but the query interface is still the same as now, so it isn't much use yet. I know it is a bit lame saying 'next version', but I'm on track for that.

Still, I'd honestly like to know about any and all stat failures. Benchmarking and testing only goes so far.

**Comment by evanmcc** [comment]
Often is, unfortunately, very rarely except at the worst possible times,
i.e. the system is heavily loaded.  This is the most common failure I have
seen so far:

curl -s 'localhost:8098/stats'
<html><head><title>500 Internal Server
Error</title></head><body><h1>Internal Server Error</h1>The server
encountered an error while processing this request:<br><pre>{error,
    {error,function_clause,
        [{lists,foldl,
             [#Fun<mochijson2.3.107902433>,
              <actual customer stats elided>
              {error,
                  {timeout,
                      {gen_server,call,
                          [riak_core_vnode_manager,all_vnodes]}}}],
             [{file,"lists.erl"},{line,1196}]},
         {mochijson2,json_encode_proplist,2,
             [{file,"src/mochijson2.erl"},{line,170}]},
         {riak_kv_wm_stats,produce_body,2,
             [{file,"src/riak_kv_wm_stats.erl"},{line,77}]},
         {webmachine_resource,resource_call,3,
             [{file,"src/webmachine_resource.erl"},{line,169}]},
         {webmachine_resource,do,3,
             [{file,"src/webmachine_resource.erl"},{line,128}]},
         {webmachine_decision_core,resource_call,1,
             [{file,"src/webmachine_decision_core.erl"},{line,48}]},
         {webmachine_decision_core,decision,1,
             [{file,"src/webmachine_decision_core.erl"},{line,532}]},
         {webmachine_decision_core,handle_request,2,
             [{file,"src/webmachine_decision_core.erl"},{line,33}]}]}}</pre><P><HR><ADDRESS>mochiweb+webmachine
web server</ADDRESS></body></html>

**Comment by russelldb** [comment]
Ok, well…I think we can do something about that just in riak_kv_wm_stats, by filtering un-JSONable values out of the stats list.

Is it that stat / reason most often (the 'all_vnodes' call?) 'cos that looks like we _shouldn't_ do it anyway, I imagine it is part of the riak_core_stats vnode_queues stat.

Let me see if I can get something done fast as a bandaid. Longer term fine grained querying with the per-stat cache that I've made will solve this.

**Comment by evanmcc** [comment]
may want to replace with null rather than filter out, so that people know
that a value could not be fetched, rather than it just disappearing.

**Comment by russelldb** [comment]
I'll see what I can do…might not be able to tell _which_ stat is the cause of the problem…but yes, I'll do my best to maintain the same structure and replace a key with "unavailable" if possible.

**Comment by russelldb** [comment]
At the moment the output of `/stats` is simply the joined list of riak_kv stats and riak_core stats. 

I don't think I can fix this nicely for 1.3. I can fix it well enough, but the granularity is at the level of the application. So if there is a problem with any riak_kv stat, you don't get any kv stats, only core. If the problem is with a core stat (as in the case above) you don't get any core stats, only KV.

Is that acceptable?

**Comment by evanmcc** [comment]
That seems better.

@jtuple had mentioned that there was some way (changing the protectedness
of the ets table that all_vnodes is accessing, I think), to avoid that call
and still get that stat when the vnode manager is backed up or sad.

**Comment by russelldb** [comment]
Surely. I will do that too.

**Comment by russelldb** [comment]
@evanmcc do we consider this something we can get into 1.3? The changes so far are minimal and I think it is warranted. I can have a PR by the end GMT day no problem.

**Comment by evanmcc** [comment]
You have my vote; I think that any situation in which we increase
availability of stats is a real win.  That it'll make the vnode manager
less busy is a plus.

**Comment by russelldb** [comment]
So, this is 'fixed' in 1.3.1, in so much as a stat calculation that errors will get you a warning in the log and an `unavailable` in the output from `/stats` or `riak-admin status`, does that cover it?

**Comment by evanmcc** [comment]
sounds good to me.

**Comment by russelldb** [comment]
Pretty sure this is addressed passably for now.
