### ISSUE TITLE
when n_val=1 a call to rand_uniform(1, 1) results in badarg and causes kv vnode to exit

### ISSUE THREAD

**Issue by gburd** [basho/riak_kv#445]
https://github.com/basho/riak_kv/blob/master/src/riak_kv_put_fsm.erl#L211
ssumes that length(Preflist2) > 1 which it isn't when n_val = 1 for that bucket.  Calling rand_uniform(1, 1) is a badarg and causes this to fail.  The simple fix is to check the length of Prelist2 before using it in rand_uniform/2.  A quick audit of other uses of rand_uniform in Riak might find similar mistakes.

**Comment by evanmcc** [comment]
fixed by: https://github.com/basho/riak_kv/pull/453
