### ISSUE TITLE
Consider exposing vector clocks in an easier-to-manipulate format.

### ISSUE THREAD

**Issue by evanmcc** [basho/riak_kv#446]
Right now we use erlangs term_to_binary to encode the vector clock, which means that without using the erlang client, most people can't do anything with that information even if they wanted to, unless they're willing to write and support a version of binary to term in their target language.   

I have a partially written python version, but it isn't small and wasn't fun to write.  

Rather than duplicating that effort for all clients, it might be better to decide on an standard output format that we can produce and optionally consume, that would allow the user to actually use the data that is encoded there.

**Comment by seancribbs** [comment]
Except for debugging purposes, I'm -1 on this. The clients shouldn't need to know how to read or manipulate vclocks. What benefit would a normal user get from inspecting the vclock?

**Comment by evanmcc** [comment]
There's a request here:
http://lists.basho.com/pipermail/riak-users_lists.basho.com/2012-December/010378.html
A customer mentioned a similar use case the other day.

Mostly I would imagine that users would use that information for client-level sibling resolution strategies that we don't currently support.

**Comment by seancribbs** [comment]
@evanmcc Yes, but I don't think the vector clock is going to give them the information they seek.

**Comment by evanmcc** [comment]
Never useful, even in the case where someone is trying to figure out the ordering of writes?

**Comment by seancribbs** [comment]
It won't tell you that, no. It will tell you the last vnode to have made a write (and when when that was) but not which write that was.
