### ISSUE TITLE
Negative clock deskew can cause stats to fail

### ISSUE THREAD

**Issue by angrycub** [basho/riak_kv#452]
Looking at `riak_kv_put_fsm:add_timing`, it uses `os:timestamp()` to provide time.  If NTP decides to set the clock backward to deskew, then `timer:now_diff(StageEnd, StageStart)` could return a negative. Which will cause `/stats` to return **500 - Internal Server Error**s until the negative falls out of the histogram window. 

Suggestion is to not capture negative timing statistics

Steps to reproduce:
- From `riak attach` run:
  
  ```
  folsom_metrics:notify_existing_metric({riak_kv,node_put_fsm_time},-9999,histogram).`
  ```
- From a browser make a call to /stats

Result:
- Calls to /stats fail with a 500
- The following output is logged on a call to /stats

```
15:44:13.936 [error] Error in process <0.5758.0> on node 'riak@127.0.0.1' with exit value: {badarith,[{bear,scan_values,2,[]},{bear,get_statistics,1,[]},{lists,keysort,2,[]}]}
15:44:13.941 [error] webmachine error: path="/stats"
{error,{error,function_clause,[{proplists,delete,[disk,{error,{badarith,[{bear,scan_values,2,[]},{bear,get_statistics,1,[]},{lists,keysort,2,[]}]}}],[{file,"proplists.erl"},{line,362}]},{riak_kv_wm_stats,get_stats,0,[{file,"src/riak_kv_wm_stats.erl"},{line,88}]},{riak_kv_wm_stats,produce_body,2,[{file,"src/riak_kv_wm_stats.erl"},{line,77}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,169}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,128}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,532}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,33}]}]}}
```

**Comment by russelldb** [comment]
Raised an issue with bear (https://github.com/boundary/bear/issues/7) for discussion. I think though, for safety, we should drop negative readings at source in Riak. So I'm doing that for now. Will keep you posted.

**Comment by evanmcc** [comment]
@russelldb did something happen with this one?

**Comment by russelldb** [comment]
Not yet. Ideally it would be fixed in Folsom.

**Comment by reiddraper** [comment]
Moving to 2.1 milestone. Speak up if there are any objections, please.
