### ISSUE TITLE
What is riak_kv_vnode:local_get/2 for, seems unused. Can delete?

### ISSUE THREAD

**Issue by russelldb** [basho/riak_kv#466]
https://github.com/basho/riak_kv/blob/master/src/riak_kv_vnode.erl#L196

Same question for `riak_kv_vnode:local_put` too, I guess.

**Comment by jonmeredith** [comment]
It got added with AAE https://github.com/basho/riak_kv/commit/7fca49d39825ef6c7861620129e179f3b21cf3fa but is a generally useful thing for debug from the console.

**Comment by russelldb** [comment]
Ah, thanks.
