### ISSUE TITLE
HTTP list buckets fails if non-UTF-8 bucket exists

### ISSUE THREAD

**Issue by shino** [basho/riak_kv#468]
After storing an object to non UTF-8 bucket, list buckets via HTTP fails.

```
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request:<br><pre>{error,{exit,{ucs,{bad_utf8_character_code}},
             [{xmerl_ucs,from_utf8,1,[{file,"xmerl_ucs.erl"},{line,185}]},
              {mochijson2,json_encode_string,2,
                          [{file,"src/mochijson2.erl"},{line,186}]},
              {mochijson2,'-json_encode_array/2-fun-0-',3,
                          [{file,"src/mochijson2.erl"},{line,157}]},
              {lists,foldl,3,[{file,"lists.erl"},{line,1197}]},
              {mochijson2,json_encode_array,2,
                          [{file,"src/mochijson2.erl"},{line,159}]},
              {mochijson2,'-json_encode_proplist/2-fun-0-',3,
                          [{file,"src/mochijson2.erl"},{line,167}]},
              {lists,foldl,3,[{file,"lists.erl"},{line,1197}]},
              {mochijson2,json_encode_proplist,2,
                          [{file,"src/mochijson2.erl"},{line,170}]}]}}</pre><P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></body></html>
```

Environment:
- R15B01
- riak.git at 09c1a419800ca61918951a25ae583566f67107a3

Steps to reproduce:

```
$ make stagedevrel
$ dev/dev1/bin/riak console
$ cat ./list_buckets_non_utf8.sh
#!/bin/bash

HTTP_PORT=10018
BUCKET='%FF'
KEY=test_key

curl -v -s \
    -X PUT \
    -d '{"bar": "baz"}' \
    -H "Content-Type: application/json" \
    http://localhost:${HTTP_PORT}/buckets/${BUCKET}/keys/${KEY} \

curl http://localhost:${HTTP_PORT}/buckets/${BUCKET}/keys/${KEY}
echo

curl -i http://localhost:${HTTP_PORT}/buckets?buckets=true
$ ./list_buckets_non_utf8.sh
```

**Comment by alman-one** [comment]
+1

**Comment by kuenishi** [comment]
I'm not sure how to handle this, because response of most http APIs are always JSON. JSON does handle only UTF-8 as string data, never as raw binary. So this is not intended but very straightforward behaviour. My suggestion is to add a new option like `http://hostname:8098/buckets?buckets=true&binary=true` and `http://hostname:8098/buckets/spam/keys?keys=true&binary=true` . Then the output is printed as some other format that can handle binary, like protobuf with content-type  `application/octet-stream` .

**Comment by kuenishi** [comment]
oh this wasn't closed.

**Comment by stephen-mw** [comment]
Unfortunately affecting me as well. As far as I know I don't have any strangely encoding buckets. s3cmd displays them without errror.

**Comment by shino** [comment]
@stephen-mw s3cmd? If you use Riak CS, Riak CS uses non-UTF-8 names for Riak buckets.

**Comment by stephen-mw** [comment]
The problem is that I can interact with my riak-cs buckets with s3cmd without issue. However if I try and use the HTTP API I get the error you displayed.
