### ISSUE TITLE
Riak calculates more stats than it needs for the `/stats` and `riak-admin status` end points

### ISSUE THREAD

**Issue by russelldb** [basho/riak_kv#505]
In 1.3 many new stats were added. When the stats are calculated we calculate all `riak_kv` stats. We now keep stats per vnode and we break down the get and put fsms into timings per stage. Histograms are the most expensive stats to calculate and almost all the new stats are histograms.

The correct thing to do is calculate the minimum number of stats needed to support the endpoints.

**Comment by russelldb** [comment]
Addressed by https://github.com/basho/riak_kv/pull/506

**Comment by jrwest** [comment]
can this be closed since #506 was merged?

**Comment by russelldb** [comment]
I guess. Or should we wait until the customer closes the related ticket?

**Comment by jrwest** [comment]
wasn't aware of related ticket. idk, safest to wait?

**Comment by russelldb** [comment]
Closing, since merged.
