### ISSUE TITLE
multibackend invalid capabalities

### ISSUE THREAD

**Issue by jrwest** [basho/riak_kv#507]
The multibackend claims to have the capabalities that are the intersection of all "sub-backend" capabilities. However, the only thing the multi backend is capable of currenlty is `async_fold` because of the implementation of `riak_kv_multibackend:capabilities/1`. The function folds over all sub-backends and takes the intersection of the accumulator set and the sub-backends capabilities. However, Acc0 is the empty set and and set intersection w/ empty set is always the empty set. 

A simple fix would be to use `lists:map` + `ordsets:intersection/1` instead.

```
1> ordsets:intersection(ordsets:new(), ordsets:from_list([indexes])).
[]
```

https://github.com/basho/riak_kv/blob/master/src/riak_kv_multi_backend.erl#L104-L106

**Comment by jtuple** [comment]
Resolved in #509 / #504
