### ISSUE TITLE
HTTP API tombstone reporting

### ISSUE THREAD

**Issue by broach** [basho/riak_kv#518]
With the HTTP API regarding tombstones here's what we currently have:
1. If _only_ a tombstone exists when you do a GET for a key, you will
   receive a 404 but it will contain the `X-Riak-Vclock` header. A "normal" 404 (when there's no object) will not have this header.
2. If there is a set of siblings, and one of them is a tombstone:
   - Retrieving all the siblings at once by including `Accept:
     multipart/mixed` in the GET request will return all the siblings, and the
     tombstone will include the `X-Riak-Deleted` header
   - Retrieving each sibling manually by adding ?vtag=XXXXXX to the GET
     will (unfortunately) return a `200 OK` for the tombstone but it will
     have an empty body (`Content-Length: 0`).

It seems the easiest way to approach this since we're returning a 404 in `1.` is to add the `X-Riak-Deleted` header there for consistency with `2a.`  

In the case of `2b.` ... ? @seancribbs is lobbying that we remove the fetch each sibling via the `?vtag=XXXXX` method since there's no logical reason to do so. At the very least we should add the `X-Riak-Deleted` header (and IMHO make it return a 404).

**Comment by seancribbs** [comment]
Resolved by #520
