### ISSUE TITLE
Sidejob adjustments and visibility work.

### ISSUE THREAD

**Issue by evanmcc** [basho/riak_kv#570]
For release, we should: 
- add +P 265000 to vm.args
- change the default riak_kv:fsm_limit to 50000, add it to app.config with commentary.
- add the sidejob stats: usage, rejected_60s, rejected_total, in_rate, and out_rate to the stats blob

**Comment by evanmcc** [comment]
also need to adjust default +zdss value, doing some benchmarking now to find a better default.

**Comment by slfritchie** [comment]
Note that "better" has several different meanings.  Smaller +zdss values will mean smaller `usleep(3)` pauses and thus hopefully lower latency, but the smaller sleep pauses will also significantly raise the amount of CPU time that an idle VM will spend spinning looking for work to do (and the associated power consumption and excess heat and ...).

**Comment by evanmcc** [comment]
config stuff adjusted in https://github.com/basho/riak/pull/336, but visibility stuff is not in yet.  Possibly just 1.4? @jonmeredith @jtuple opinions?

**Comment by evanmcc** [comment]
Fixed, closing.
