### ISSUE TITLE
Create a working dialyzer make target

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_kv#580]
The current one refers to `apps/...`, which doesn't even exist.

**Comment by engelsanchez** [comment]
@reiddraper Maybe we should close this and continue herding #524 ?

**Comment by slfritchie** [comment]
Pulling PRs out of the freezer ... it feels quite stale, especially since the string "apps/" doesn't appear in "develop"'s `Makefile` any longer.

**Comment by jtuple** [comment]
This has been fixed by #808
