### ISSUE TITLE
Add timeout to 2i endpoints

### ISSUE THREAD

**Issue by russelldb** [basho/riak_kv#610]
It seems 2i _never_ had timeouts. Which was fine while the coverage FSM ignored timeouts anway.

However, this fix https://github.com/basho/riak_core/pull/332 means 2i _must_ provide timeouts.

**Comment by graphex** [comment]
Since client support for the timeout parameter is spotty, would it be possible for a fix to incorporate a default timeout setting into app.config?

**Comment by russelldb** [comment]
@graphex we have done that. (add `{secondary_index_timeout, non_neg_integer()}` to your app.config settings for riak_kv, the unit is milliseconds and `0` means infinity (no timeout).)

Fixed for 1.4.1
