### ISSUE TITLE
HTTP index stream blows up on timeouts (1.4.1)

### ISSUE THREAD

**Issue by seancribbs** [basho/riak_kv#625]
The handling of timeout responses from the index FSM in the WM resource is broken. Specifically, [these lines](https://github.com/basho/riak_kv/blob/master/src/riak_kv_wm_index.erl#L222-L232) in `index_stream_helper`:

``` erlang
                {ReqID, Error} ->
                    lager:error("Error in index wm: ~p", [Error]),
                    ErrorJson = mochijson2:encode({struct, [{error, Error}]}),
                    Body = ["\r\n--", Boundary, "\r\n",
                            "Content-Type: application/json\r\n\r\n",
                            ErrorJson],
                    {iolist_to_binary(Body), done}
            after 60000 ->
                    {error, timeout}
            end
```

When the variable `Error` is `{error, timeout}`, JSON encoding fails. When the after block fires, an incompatible streaming term is returned to Webmachine.

I discovered these bugs while working on basho/riak-python-client#272. To provoke, checkout the PR branch and run this (assuming all else is installed correctly):

``` bash
python -m unittest riak.tests.test_all.RiakHttpTransportTestCase.test_index_timeout
```

I receive two possible failures, shown below:

```
======================================================================
ERROR: test_index_timeout (riak.tests.test_all.RiakHttpTransportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "riak/tests/test_2i.py", line 425, in test_index_timeout
    for i in bucket.stream_index('field1_bin', 'val1', timeout=1):
  File "riak/client/index_page.py", line 66, in __iter__
    for result in self.results:
  File "riak/transports/http/stream.py", line 153, in next
    message = super(RiakHttpIndexStream, self).next()
  File "riak/transports/http/stream.py", line 103, in next
    self.read_until_boundary()
  File "riak/transports/http/stream.py", line 128, in read_until_boundary
    self._read()
  File "riak/transports/http/stream.py", line 44, in _read
    chunk = self.response.read(self.BLOCK_SIZE)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 597, in _read_chunked
    raise IncompleteRead(''.join(value))
IncompleteRead: IncompleteRead(0 bytes read)

----------------------------------------------------------------------
```

```
======================================================================
ERROR: test_index_timeout (riak.tests.test_all.RiakHttpTransportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "riak/tests/test_2i.py", line 425, in test_index_timeout
    for i in bucket.stream_index('field1_bin', 'val1', timeout=1):
  File "riak/bucket.py", line 474, in stream_index
    timeout=timeout)
  File "riak/client/operations.py", line 179, in stream_index
    timeout=timeout)
  File "riak/transports/http/transport.py", line 336, in stream_index
    "supported on %s" % self.server_version.vstring)
NotImplementedError: Secondary index streaming is not supported on 1.0.0

----------------------------------------------------------------------
```

Based on some [sleuthing with Wireshark](https://s3.amazonaws.com/uploads.hipchat.com/20796%2F98701%2Fjs3zrygvxi8md5e%2Fpython-http.txt), the second seems to be caused by the dreaded "lingering 400" bug in Mochiweb, which results in misreporting the server version when the client accesses `/stats`. I'm not sure how this problem regressed, but it is possible that the `500` response from the preceding request caused the `400`.

**Comment by seancribbs** [comment]
Note that these messages are reported in error.log when running the unit tests:

```
2013-08-06 13:31:03.950 [error] <0.17513.8> Webmachine error at path "/buckets/uclzxiwrparr/index/field1_bin/val1" : {error,{error,timeout}}
2013-08-06 13:31:03.957 [error] <0.17513.8>@riak_kv_wm_index:index_stream_helper:249 Error in index wm: {error,timeout}
2013-08-06 13:31:03.957 [error] <0.17513.8> CRASH REPORT Process <0.17513.8> with 0 neighbours exited with reason: {json_encode,{bad_term,{error,timeout}}} in mochijson2:json_encode/2 line 149
2013-08-06 13:31:20.010 [error] <0.17542.8> Webmachine error at path "/buckets/mhkblfkwzqcc/index/field1_bin/val1" : {error,timeout}
```

**Comment by russelldb** [comment]
Ok. This issue should be against 1.4.0, it was caused by the "fix" to riak core coverage fsm, and not the addition of a timeout param in 1.4.1. The addition of the timeout was caused by the same issue as this, but that is the only way they are related.

I can see it needs fixing, but neither @rzezeski or I caused it, nor was it under review, the issue here is with the ill considered fix to riak_core_coverage_fsm that didn't address all the users of that FSM. The 1.4.1 timeout fixes address the worst effects of that change to 2i, but this one got through. I think the _real_ issue is the awful test coverage on 2i, something I added to enormously, but is still not high enough, clearly. The addition of a riak_test to expose this bug would be of the most value.

**Comment by seancribbs** [comment]
@russelldb Sure, I think it's clear it was not caused by the 1.4.1 update, just exposed by it. I think in general, we could be testing the unhappy-path a bit more. That said, I'll be looking into the fix tomorrow -- especially the 400 error -- I just wanted to make sure I recorded the bug and its symptoms before I ran out of juice.

**Comment by engelsanchez** [comment]
@seancribbs this is all now working after https://github.com/basho/riak_kv/pull/644 in 1.4.2, right?

**Comment by seancribbs** [comment]
@engelsanchez I believe so. @russelldb ?

**Comment by engelsanchez** [comment]
Well, open again if there are lingering issues.
