### ISSUE TITLE
You can upset your cluster by submitting a non-numeric n_val

### ISSUE THREAD

**Issue by russelldb** [basho/riak_kv#666]
And I imagine similar damage with other bucket properties. We have a simple bucket validation "Framework" in riak now, add some validators for n_val and other number properties so riak cuts fewer hands that try to hold it.

**Comment by russelldb** [comment]
See https://github.com/basho/riak_kv/pull/667 and https://github.com/basho/riak_test/pull/389

**Comment by jrwest** [comment]
addressed by merge of https://github.com/basho/riak_kv/pull/770
