### ISSUE TITLE
riakc_pb_socket:set_bucket with yz_index prop doesn't apply the property

### ISSUE THREAD

**Issue by elight** [basho/riak_kv#701]
Attempt to set a bucket prop of yz_index. Check the bucket props after.  The property isn't being set.

This feature does work via HTTP just not PB.

**Comment by seancribbs** [comment]
Do you have the most up-to-date riak_pb? https://github.com/basho/riak_pb/blob/develop/src/riak_pb_codec.erl#L404

**Comment by elight** [comment]
Ah my rebar.config may appears to be pegged to an older revision... :-/

**Comment by seancribbs** [comment]
Cool, closing.
