### ISSUE TITLE
consistent ops should have a fast failure path when ensembles aren't enabled

### ISSUE THREAD

**Issue by evanmcc** [basho/riak_kv#713]
right now his behavior is unhandled

**Comment by reiddraper** [comment]
@evanmcc @jtuple @andrewjstone is this a 2.0 blocker?

**Comment by jtuple** [comment]
This seems like a 2.0 blocker, and is easy to fix. Assigning to 2.0 RC for now, will decide to punt later if we decide it's a non-issue / run out of time.

/cc basho/riak#536
