### ISSUE TITLE
Handoff fails with TTL and memory backend

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak_kv#724]
During a PUT, if TTL is enabled, the memory backend prepends a timestamp to the riak_object as a tuple[1]. This causes riak_core_pb:encode to fail during handoff because it is expecting just a simple erlang binary, not a tuple.

This issue requires not using TTL and removing all data written with a TTL(either with a delete or a node restart).

[1] https://github.com/basho/riak_kv/blob/develop/src/riak_kv_memory_backend.erl#L211

**Comment by evanmcc** [comment]
A quick glance at the code suggests that folds should be doing the right thing already, although clearly they're not.  redbugging riak_kv_memory_backend strip_timestamp might indicate what's going wrong.

**Comment by bsparrow435** [comment]
Adding a console.log message indicating the failure on the send side of handoff:

2013-11-06 17:07:34.723 [error] <0.24845.46> gen_server <0.24845.46> terminated with reason: no function clause matching riak_core_pb:encode({ts,{1383,746117,164645}}, {{ts,{1383,746117,164645}},<<131,104,7,100,0,8,114,95,111,98,106,101,99,116,109,0,0,0,52,56,51,...>>})

**Comment by bsparrow435** [comment]
The riak_object binary was removed because it is active customer data. <> is actually a riak_object erlang binary

**Comment by evanmcc** [comment]
looks like @Vagabond fixed this for develop in https://github.com/basho/riak_kv/commit/d48902266e8ba43db44ee1ac3fd8202e5e090557.  Is there enough demand to backport this?

**Comment by jtuple** [comment]
Issue resolved on develop. Unclear if we want to backport. Closing issue for now.
