### ISSUE TITLE
[DOWNGRADE?] The new dvv stuff doesn't play well with JS map-reduce

### ISSUE THREAD

**Issue by rzezeski** [basho/riak_kv#779]
While running Yokozuna's map-reduce test I saw the following error.

```
[{xmerl_ucs,from_utf8,1,[{file,\"xmerl_ucs.erl\"},{line,185}]},
                         {mochijson2,json_encode_string,2,[{file,\"src/mochijson2.erl\"},{line,186}]},
                         {mochijson2,'-json_encode_proplist/2-fun-0-',3,[{file,\"src/mochijson2.erl\"},{line,167}]},
                         {lists,foldl,3,[{file,\"lists.erl\"},{line,1248}]},
                         {mochijson2,json_encode_proplist,2,[{file,\"src/mochijson2.erl\"},{line,170}]},
                         {riak_kv_wm_mapred,send_error,2,[{file,\"src/riak_kv_wm_mapred.erl\"},\n                                  {line,116}]},
                         {riak_kv_wm_mapred,pipe_mapred_nonchunked,3,[{file,\"src/riak_kv_wm_mapred.erl\"},{line,260}]},
                         {webmachine_resource,resource_call,3,[{file,\"src/webmachine_resource.erl\"},{line,186}]}]}}
```

After adding a logging call to the code I noticed this in the server log.

```
2013-12-23 21:39:48.357 [error] <0.252.0>@riak_kv_wm_mapred:pipe_mapred_nonchunked:260   [{phase,0},{error,<<"bad_json">>},{input,<<"{ok,{r_object,{<<\"mr_index\">>,<<\"b1\">>},<<\"key_4\">>,[{r_content,{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[[<<\"Links\">>]],[],[[<<\"dot\">>|{<<92,176,215,10,82,184,173,140>>,{1,63555053987}}]],[],[],[],[],[],[[<<\"content-type\">>,97,112,112,108,105,99,97,116,105,111,110,47,106,115,111,110],[<<\"X-Riak-VTag\">>,55,51,99,97,74,86,50,100,83,102,65,76,88,56,90,70,85,100,80,67,101,77]],[[<<\"index\">>]],[],[[<<\"X-Riak-Last-Modified\">>|{1387,834787,399263}]],[],[[<<\"...\">>]]}}},...}],...},...}">>}]
```

Notice the `<<\"dot\">>|{<<92,176,215,10,82,184,173,140>>,{1,63555053987}`. Mochijson cannot properly encode the dot in this form. It is my feeling that the dot should not be exposed for JS map-reduce. The function `riak_object_json:jsonify_metadata` needs to be fixed.

**Comment by russelldb** [comment]
I'll look it at UK am. Thanks for catching it.

**Comment by rzezeski** [comment]
@russelldb Don't worry about it. I'm already working on fix.

**Comment by russelldb** [comment]
@rzezeski thanks mate.

**Comment by rzezeski** [comment]
I'm reopening this issue to track downgrade support as mentioned by @jonmeredith. I fixed the issue in 2.0 but @russelldb was worried about downgrades since 1.4.x has no notion of a dot.

**Comment by russelldb** [comment]
Decided to tackle this as
1. Release note it saying "if you use JS mapreduce, and you may want to downgrade to 1.4 after upgrading to 2.0, then please switch dvv.enabled=false, as `dots` are not encoded for JS. If you forget or chose not to, we can provide a patched 1.4 riak_kv_mapreduce beam that enables you to downgrade and ignore dots"
2. Add the mapreduce JS patch code from ryan to a 1.4 branch so there is a downgrade target that works with dots.

**Comment by rzezeski** [comment]
Is this issue still open for a reason or did we just forget to close it?

**Comment by rzezeski** [comment]
@russelldb Was documentation added for (1) and was the (2) branch ever made? Should this issue still be open?
