### ISSUE TITLE
existing data under bucket type disappears at mapred with keylist input

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_kv#790]
An existing keydata disappears and handled badly at `riak_kv_pipe_get:bkey/1` .

To reproduce, with a fresh Riak node bucket type prepared:

``` sh
$ dev/dev1/bin/riak-admin bucket-type create t '{"props":{}}'
$ dev/dev1/bin/riak-admin bucket-type activate t
$ dev/dev1/bin/riak-admin bucket-type list
t (active)
$ curl -X PUT http://localhost:10018/types/t/buckets/b/keys/k -d 'foobar'
```

Then using erlang client:

``` erlang
Eshell V5.10.4  (abort with ^G)
1> {ok,C}=riakc_pb_socket:start_link(localhost,10017).
{ok,<0.35.0>}
2> riakc_pb_socket:get(C,{<<"t">>,<<"b">>},<<"k">>).
{ok,{riakc_obj,{<<"t">>,<<"b">>},
               <<"k">>,
               <<107,206,97,96,96,96,204,96,202,5,82,28,71,131,54,114,7,
                 29,244,72,203,96,74,...>>,
               [{{dict,3,16,16,8,80,48,
                       {[],[],[],[],[],[],[],[],[],[],[],[],...},
                       {{[],[],[],[],[],[],[],[],[],[],...}}},
                 <<"foobar">>}],
               undefined,undefined}}
3> riakc_pb_socket:mapred(C,[{{<<"t">>,<<"b">>},<<"k">>}], []).
{ok,[{0,[{{<<"t">>,<<"b">>},<<"k">>}]}]}
4> riakc_pb_socket:mapred(C,[{{<<"t">>,<<"b">>},<<"k">>}], [{map,{modfun,riak_kv_mapreduce,map_object_value},undefi
ned,false}]).
{error,<<"{\"phase\":0,\"error\":\"function_clause\",\"input\":\"{{error,notfound},{<<\\\"t\\\">>,<<\\\"b\\\">>},<<\\\"k\\\">>}\",\"type\":\"er"...>>}
```

The reason for this is, BKey `{{Type,Bucket}, Key}` matches [first clause of riak_kv_pipe_get:bkey/1](https://github.com/basho/riak_kv/blob/ea0edcad1c2e6589bc09f493c4c6f57928e6644a/src/riak_kv_pipe_get.erl#L164) and later pipe handles `{Type, Bucket}` as a complete  BKey, which leads to not found at next pipe phase. Just deleting this line may solve this problem, but I'm not sure why this clause exists - any thoughts?

I used `ec02cb6e9ba2c5a5463fb` .

**Comment by engelsanchez** [comment]
Unfortunately we had to go with a different order to make bucket types backwards compatible: https://github.com/basho/riak_kv/pull/703

So to include a type you will have to use the list form, with undefined keydata as a 3rd element and the bucket type as the fourth element. Bucket type needs to be the 4th element in JS as well.

**Comment by kuenishi** [comment]
I tried `riakc_pb_socket:mapred(C,[[<<"b">>,<<"k">>,undefined,<<"t">>]], [{map,{modfun,riak_kv_mapreduce,map_object_value},undefined,false}]).` but got 

```
{error,<<"{inputs,{\"Inputs target tuples must be {B,K} or {{B,K},KeyData}:\",\n         [[<<\"b\">>,<<\"k\">>,undefined,<<\"t"...>>}
```

 Looks like it's validated at `riak_kv_mapred_term:valid_input_targets/1` and the four-element list doesn't match.

**Comment by engelsanchez** [comment]
Kota, in your case using {{{Type, Bucket}, Key}, undefined} should work.  The list is only good for JS functions, sorry for misleading you. While trying that on a default bucket though, I found yet another problem: the {<<"default">>, Bucket} bucket doesn't hash the same as Bucket, so the object is not found, and I'm getting errors on not found handling also. I'll track that on a separate issue. If the above works for you, feel free to close the issue or propose an improvement on this horrible backwards compatibility mess.  At the very least I should update the riak erlang client documentation to point this out.

**Comment by engelsanchez** [comment]
Actually, I was passing an incorrect parameter when I saw the error mentioned above. You may encounter it too: I had to use: {map,{modfun,riak_kv_mapreduce,map_object_value},<<"filter_notfound">>,true}. Then, the {{{T,B},K},KD} does work with the Erlang client.

**Comment by engelsanchez** [comment]
@kuenishi did you see my reply above? I'm going to close this unless you object soon

**Comment by kuenishi** [comment]
@engelsanchez I've been in vacation and now I found it worked!

``` erl
6> riakc_pb_socket:mapred(C,[{{{<<"t">>,<<"b">>},<<"k">>},undefined}], [{map,{modfun,riak_kv_mapreduce,map_object_value},undefined, true}]). 
{ok,[{0,[<<"{\"a\": \"b\"}">>]}]}
```

Thank you!
