### ISSUE TITLE
Mutated objects are not unmutated on all code paths

### ISSUE THREAD

**Issue by jtuple** [basho/riak_kv#791]
The new mutator logic mutates objects right before storing the object to disk, and is supposed to unmutate the object when reading from disk (thus, the higher levels of Riak don't know about mutated objects).

However, `riak_kv_mutator:mutate_get/1` is only called inside `riak_kv_vnode:do_get_term/3` which is not the only code path that reads objects from disk.

Several code paths in the vnode directly call `do_get_object/4` or `do_get_binary/4` which currently return the mutated object. This is broken. This is especially bad for `do_diffobj_put/3` that uses `do_get_object` directly, and then merges the mutated object with the new incoming object.

Basho internal discussion on this issue:

https://basho.hipchat.com/history/room/138541/2013/11/07?q=mutator#14:50:33
https://basho.hipchat.com/history/room/154790/2013/11/07?q=mutator#14:59:44

**Comment by russelldb** [comment]
Not sure I have a good enough handle on this. Not convinced that rehash wants the mutate_get object, but instead it probably wants the actual fake on disk, @jtuple ?

**Comment by jtuple** [comment]
AAE should always be operating on full/real objects to ensure that all trees have consistent hashes across all replicas. Mutation changes the objects non-uniformly. For example with reduced N mutator, some replicas store full object, other replicas store reduced "metadata/promise" object. If AAE uses the mutated object, different replicas would have different hashes and AAE would believe replicas are divergent when they're not.

So, no, we definitely don't want the on-disk object that is potentially different between replicas. We want the unmutated object. The realtime inserts into AAE should use the real object. Likewise, when we do a fold over K/V data to rebuild AAE trees, we need to unmutate objects before inserting them into the AAE tree. And we need to be sure that the object hash stays the same across all the mutate/unmutate roundtrip.

So, lots of code to change / double check.

In the [original proposal](https://gist.github.com/Vagabond/658074a3ba260787bf08) for metadata-only objects, the plan was for mutation to store the hash of the original object as metadata, and have AAE just use that metadata both when inserting in realtime and when folding over the K/V data during a rebuild. This would trivially ensure the hash was preserved regardless of the round-trip effect of mutation. But, looks like that wasn't the approach we took. Of course, I suppose we _could_ update code to do that if needed (for example, if the current approach turns out to not preserve hash across mutation and can't be easily changed to do so). However, that only fixes AAE. Other areas of RIak might be sensitive to the object changing when across the mutation roundtrip as well.

In any case, as far as I understand mutation as it exists today, the intention was for it be at the lowest level in Riak with mutation/umutation happening at the vnode/backend layer. With the explicit goal that the `riak_object` seen at the next layer and up is a full object that is identical to the object you'd see without mutation enabled. To that end, it seems like we just need to 1) ensure mutate/unmutate produces identical object to mutation-disabled Riak and 2) ensure all code paths that read/write things to disk in the vnode do the mutate/unmutate dance.

**Comment by jtuple** [comment]
I just noticed question 5 in basho/riak_repl#502 so I wanted to clarify expectations. To make this simple, I'm going to talk about reduced N mutation specifically, rather than mutation generally.

Let's say I have a cluster that is reducing `N=3` to `N=1`, so remote objects stored on this cluster end up with 1 real object on vnode A and 2 reduced objects on vnodes B and C.

First, per my comment above, I expect AAE to be storing hashes based on the real riak_object (specifically, a hash that's identical to a riak_object without mutation enabled at all). This hash would be the same for all vnodes, regardless of it the vnode is storing reduced or full objects.

If B or C lose their reduced object, I expect AAE to eventually notice and trigger a repair. I expect this repair to generate a full object that is once again reduced by vnode B or C before being written to disk. In other words, I expect a missing reduced object to be repaired to an identical reduced object.

Likewise, if A loses it's full object, I expect AAE to eventually notice, trigger a repair, and generate a full object on A.

To be clear, AAE should trigger read repair. This should send a get to all vnodes, which will directly return a full object or return a full object that is generated by unmutating a reduced object (via a local or proxy_get). The get FSM does normal read repair, sending writes to vnodes as necessary. Since these incoming objects should have "cluster of record" entries in their metadata, the local vnodes should trigger reduced N mutation -- storing either the full object directly (for vnode A) or a reduced object (for vnodes B and C).

This is what I expect. I have no idea if this is what actually occurs today, nor if this is what can be supported with the current approach, but it's the proper behavior.

Technically, I know this is broken in some cases since as discussed in my previous comment about needing to unmutate reduced objects when rebuilding hashtrees -- something we don't currently do. 

---

To explicitly reiterate my hashing expectation, I expect AAE hashes to match in all cases of mutation. hash(object when reduced N disabled) == hash(full object when reduced N enabled) == hash(unmutated reduced object).

Likewise, I expect the hash to match across all clusters for the same three cases. If not, AAE-based fullsync replication won't work. Or rather, will infinitely sync objects.

As mentioned above, the easiest way to do this might be to just store the hash of the original object in the metadata of all object types so we don't need to go through the unmutation dance to get a hash. Specifically, folding over local K/V data and then needing to do a local/proxy_get to unmutate each reduced object for the proper hash is crazy.

**Comment by russelldb** [comment]
@jtupl and whomever else is listening:-

> To make this simple, I'm going to talk about reduced N mutation specifically, rather than mutation generally.

There _is_ only reduced N mutation. The design and build of a generalised system was to get around circular dependancies between kv and repl, not to satisfy some general demand for mutation. I think it is _very_ important to remember that, unless there is some other concrete requirement I am missing.

Thanks for the rest of you comments. You've cleared up my misunderstanding. The crazy _is_ coded though.

**Comment by lordnull** [comment]
Mutators were bumped, so closing this issue for now.
