### ISSUE TITLE
Downgrade from 1.4 -> 1.2 does not revert handoff capability [JIRA: RIAK-2085]

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_kv#802]
Found while testing a customer upgrade, then downgrade scenario. Handoff from 1.4 nodes sent raw objects, while 1.2 nodes only understand zlib compressed data. The capability was still set to raw in the 1.4 nodes, even though the list of supported capabilities in the ring showed that the downgrade node couldn't handle it. The riak_core_capability server was not updating the supported list. Killing it and letting it restart would fix the issue: the supported capabilities of the downgraded cluster were taking into account and the old data format was picked.  I believe that the code to avoid updating the list from the ring based on ring ids (introduced as a large ring optimization I think?) fails in a downgrade. More debugging is necessary.

**Comment by danieldreier** [comment]
@mjbrender pretty sure this can be closed, since it seems unlikely that any more riak 1.4 functionality is going to be added.

**Comment by mbbroberg** [comment]
@danieldreier good call. 1.4 is near EOL and 1.2 definitely is.
