### ISSUE TITLE
can't set riak_kv.anti_entropy_expire as 'never'

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_kv#809]
According to [riak_kv_index_hashtree.erl](https://github.com/basho/riak_kv/blob/develop/src/riak_kv_index_hashtree.erl#L784), to prevent rebuild of aae tree it's natural extimation to set `anti_entropy.expire` as `never`, but riak_kv.schema doesn't allow to do so. This seems because in its datatype is set as `{duration, ms}` .

If you set this as `never`, ignoring all above results in:

```
> application:get_env(riak_kv, anti_entropy_expire).
{ok,error}
```

Or is that assumed that we can't set `never` as expiry?

**Comment by seancribbs** [comment]
@kuenishi That looks like a bug in the schema, we can fix it like this:

``` erlang
{datatype, [{duration, ms}, {atom, never}]}
```

**Comment by kuenishi** [comment]
Hmm, just changing riak_kv.schema like that didn't work for me. We have to dig into cuttlefish?

**Comment by seancribbs** [comment]
Did you rebuild the release after? Those are copied to the top-level "lib" directory when generating.

**Comment by kuenishi** [comment]
I'm sure and I believe in myself but now I'm losing my religion. I'll try it again with your branch.

**Comment by kuenishi** [comment]
I tried your fix `bugfix/sdc/anti-entropy-expire` (which is totally same with my local diff) and added a line to riak.conf like this:

```
## Acceptable values:
##   - one of: active, passive, active-debug
anti_entropy = active
anti_entropy.tree.expiry = never
```

But didn't work https://gist.github.com/kuenishi/8551746. As seeing your branch passes eunit, now I'm confused...

**Comment by seancribbs** [comment]
@kuenishi Would you attach the generated configs to that gist? You can get them by running  `riak config generate`.

**Comment by kuenishi** [comment]
here: https://gist.github.com/kuenishi/8551746#file-app-2014-01-22-12-19-09-config-L74
fmm, looks like it's failing in generate.

**Comment by seancribbs** [comment]
Hmm, it shouldn't generate at all, it should abort. Are there error lines logged to the console when you generate?

**Comment by kuenishi** [comment]
Nothing specific. Is it working correctly in your env? Only me? Then I can try in another env.

**Comment by seancribbs** [comment]
One more time, would you run `riak config generate -l debug`? The `-l debug` will enable more verbose output.

**Comment by kuenishi** [comment]
here: https://gist.github.com/kuenishi/8551746#file-another-exec

Wow, the error is silently ignored. The output app.**.config file is totally the same.

**Comment by seancribbs** [comment]
@kuenishi Thank you for digging in. This looks like a serious cuttlefish bug that I will work to fix this week.

**Comment by seancribbs** [comment]
@kuenishi Yes, I've traced it down to `cuttlefish_duration`, which returns `error` instead of `{error, Reason}` on a bad parse.

**Comment by seancribbs** [comment]
@kuenishi Will you pull latest cuttlefish and try again? The fix in basho/cuttlefish#112 will be in the next pre.

**Comment by kuenishi** [comment]
it worked great :boom: 

```
      {anti_entropy_tick,15000},
      {anti_entropy_concurrency,2},
      {anti_entropy_expire,never},
      {anti_entropy,{on,[]}},
```

**Comment by seancribbs** [comment]
@kuenishi Thanks, #810 is now merged.
