### ISSUE TITLE
Storing without key should generate the key name based on sha2sum(value)

### ISSUE THREAD

**Issue by cipy** [basho/riak_kv#842]
It would be useful for developers to get from Riak a confirmation that all bits sent on the wire were correctly received by the backend. This can be achieved by generating a key name as a checksum (sha2?) of the actual value/data received by Riak.

http://docs.basho.com/riak/latest/dev/references/http/store-object/#Example-Storing-Without-Key

**Comment by seancribbs** [comment]
What happens when someone rewrites the object later and it doesn't match its key anymore? For now, a combination of a large DW and return_body would accomplish the desired effect.

**Comment by cipy** [comment]
The problem with return_body is that the whole body comes back to the client, which might be expensive (both for the sender, and also for the receiver to parse and/or build check sums)

Once an update was pushed to the (named) key, the initial hint (key name =sha2sum) is lost

The feature should be just an amendment to the current implementation for keyless storage, where pushing same value/data over and over again just increases the used disk space (arguably w/o other benefits)

**Comment by cipy** [comment]
pondering a bit more on it,
sha2sum(content) would be more CPU expensive and hinder concurrency. thanks @seancribbs
