### ISSUE TITLE
AAE + ownership change race = 5 minute AAE stall

### ISSUE THREAD

**Issue by jtuple** [basho/riak_kv#846]
If the remote tree in an AAE exchange is for a partition that is changing ownership, it's possible for the exchange FSM to stall when trying to grab the remote lock, eventually timing out. As the default AAE timeout is 5 minutes, this is a noticeable stall.

Technically, this is "working as designed". The timeout triggers, the exchange fails, and the world moves on.

The main issue is the strong consistency case, which needs to perform AAE exchanges to move peers into the trusted state (when running in paranoid mode). If this race is hit, the stall can prevent an ensemble from becoming available for ~5 minutes, leaving that portion of the key space unavailable to client requests.

It's unclear how easy it is to fix this scenario, but I wanted to open an issue to document/record this issue.

The race is straightforward. The `riak_kv_exchange_fsm` calls `start_exchange_remote` on the `riak_kv_entropy_manager`. The manager handles the request, and sees that there is still a valid hashtree pid for the given tree index, gets the local concurrency lock, then forwards the request to the pid (via a cast) to get a tree lock. However, the ownership transition completes concurrently causing the hashtree pid to either already be dead or be in the process of shutting down -- either way, ignoring the message. The exchange then stalls until the timeout triggers.

Again, working as designed. But, we can probably do better.

---

The user-facing observed behavior is `riak-admin aae-status` showing missing (or highly delayed) exchange time for the partition that is going to timeout. And, ultimately, a message in the log acknowledging the timeout.

As an example.

Note the missing time for the All column for partition 3653...:

```
================================== Exchanges ==================================
Index                                              Last (ago)    All (ago)   
-------------------------------------------------------------------------------
0                                                  2.7 min       2.9 min     
365375409332725729550921208179070754913983135744   3.0 min       --          
730750818665451459101842416358141509827966271488   2.8 min       2.8 min     
1004782375664995756265033322492444576013453623296  2.7 min       2.8 min     
1096126227998177188652763624537212264741949407232  2.7 min       2.8 min     
1370157784997721485815954530671515330927436759040  2.8 min       2.9 min     
```

Eventually, we timeout:

```
[info] <0.1169.0>@riak_kv_exchange_fsm:do_timeout:386 Timeout during
exchange between
(local)
{365375409332725729550921208179070754913983135744,'dev1@127.0.0.1'} and
(remote)
{548063113999088594326381812268606132370974703616,'dev1@127.0.0.1'},
(preflist)
{365375409332725729550921208179070754913983135744,3}
```

And now, AAE can retry/complete the exchange:

```
================================== Exchanges ==================================
Index                                              Last (ago)    All (ago)   
-------------------------------------------------------------------------------
0                                                  1.8 s         2.3 s       
365375409332725729550921208179070754913983135744   824.9 ms      1.6 s       
730750818665451459101842416358141509827966271488   457.7 ms      734.6 ms    
1004782375664995756265033322492444576013453623296  29.0 ms       3.2 s       
1096126227998177188652763624537212264741949407232  2.7 s         3.2 s       
1370157784997721485815954530671515330927436759040  1.1 s         2.3 s       
```

**Comment by jtuple** [comment]
We should at least lower the default timeout from 5 minutes for 2.0.

**Comment by engelsanchez** [comment]
It sounds like we should lower the default timeout at this point like @jtuple says and postpone any bigger changes for later, right?

**Comment by engelsanchez** [comment]
@jtuple I will push a PR to lower and make the time configurable unless you have taken care of this already.

**Comment by engelsanchez** [comment]
Interesting side note: riak_kv_exchange_fsm has the same FSM timeout problem that you helped me figure out with 2i AAE. It uses the FSM timeout mechanism, but if you hit handle_info with any message the timeout disappears and it may sit there in the prepare_exchange state for ever I believe.

**Comment by engelsanchez** [comment]
@jtuple if you have a minute could you glance at the little change in #971 and see if that looks good for now.

**Comment by engelsanchez** [comment]
Closing after merging #971. @jtuple not sure if you want to file another issue for a potentially more robust solution or re-open and move this one.
