### ISSUE TITLE
Allow for simple default case for creating bucket types

### ISSUE THREAD

**Issue by jaredmorrow** [basho/riak_kv#880]
Want:  Make a simple default case for create bucket types without the need for valid json

IMHO something like this:

```
riak-admin bucket-type create bob
```

should give me a bucket type of `bob` with all the defaults (eg: N=3, allow_mult=true, backend=bitcask, etc.)

Instead it does:

```
riak-admin bucket-type create bob
Usage: riak-admin bucket-type create <type> '{"props": { ... }}'
```

**Comment by Vagabond** [comment]
It'd also be nice to have 'macros' for common bucket type configs, like ones for crdt-maps or strongly-consistant data.

**Comment by jaredmorrow** [comment]
This is a duplicate of basho/riak#423
