### ISSUE TITLE
fix validation error output in riak-admin bucket-type commands

### ISSUE THREAD

**Issue by jrwest** [basho/riak_kv#893]
example speaks for itself I think but to clarify, its not user friendly or easily readable:

```
$ riak-admin bucket-type create any '{"props": {"n_val": "abc", "consistent": "abc"}}'
Error creating bucket type any: [{n_val,not_integer},
                                 {consistent,
                                     "<<\"abc\">> is not a valid value for consistent. use \"true\" or \"false\""},
                                 {reserved_name,
                                     "The name 'any' may not be used for bucket types"}]
```

**Comment by reiddraper** [comment]
Anyone working on this?

**Comment by macintux** [comment]
I wrote similar error message cleanup code for `riak_core_console` IIRC; I'll take a look.

Here are the changes I applied to core; will take the same approach here.

https://github.com/basho/riak_core/pull/546/files

**Comment by macintux** [comment]
Digging through code looking for error tuples. I have no confidence that this is a comprehensive list, and it's possible to define additional validators in the Riak configuration, so the solution will have to be flexible with what it accepts.

``` erlang
{active, "Cannot modify active property"}
{reserved_name, "The name 'any'..."}

{claimant, "No claimant details found in existing properties"}
{claimant, "Cannot modify claimant property"}
{claimant, "Cannot update claimant property"}
{claimant, "Invalid claimant"}

{IntProp, not_integer}
{QProp, not_valid_quorum}

{consistent, "cannot update consistent property"}
{consistent, "~p is not a valid value for consistent. use \"true\" or \"false\""}

{BoolProp, not_boolean}
```

**Comment by jrwest** [comment]
all of the tuples should live in one of the registered bucket validtors + `riak_core_bucket_props`. I agree we need a general sol'n either way -- if someone adds a tuple but doesn't change the output, things should not break.

I think it would be fine to have something like:

```
do_print({IntProp, not_integer}) ->
   ....;
do_print({claimant, Error}) ->
   ....;
do_print({X,Y}) ->
  io:format("~p: ~p~n", [X, Y]).
```

**Comment by macintux** [comment]
Yeah, that's pretty much what I defined for security errors.
