### ISSUE TITLE
Synchronous writes and bitcask

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_kv#895]
The bitcask backend should allow `sync` to be set when `io_mode` is NIF.

See basho/basho_docs#960 for some discussion. Since NIF mode bitcask opens a file using `open()` and the `O_SYNC` flag as opposed to `fcntl`, the check and warning no longer apply.

Once erlang/otp#137 ships with Riak `erlang` `io_mode` will support `sync` as well.

Also see `check_fcntl` here: https://github.com/basho/riak_kv/blob/develop/src/riak_kv_bitcask_backend.erl

**Comment by evanmcc** [comment]
> The bitcask backend should allow sync to be set when io_mode is NIF.
> 
>  I think that it does actually allow it, it's just that `check_fcntl` still
> issues that spurious error?  We should maybe remove that.
> 
> See basho/basho_docs#960 https://github.com/basho/basho_docs/issues/960for some discussion. Since NIF mode bitcask opens a file using
> open() and the O_SYNC flag as opposed to fcntl, the check and warning no
> longer apply.
> 
> Once erlang/otp#137 https://github.com/erlang/otp/pull/137 ships with
> Riak erlang io_mode will support sync as well.
> 
> Steve will know when this went in.  Perhaps it should go into whatever
> we're shipping with for 2.0, if it isn't there already.

**Comment by reiddraper** [comment]
Moving to 2.1 milestone. Speak up if there are any objections, please.
