### ISSUE TITLE
riak_kv_multi_backend: extra_callback_test...*timed out*

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_kv#897]
Is this happening to anyone else? On develop: 9f6f2183bde88f32cec6b6ac206ac6eacdb54e63. If so, I'll make a fix to increase the test timeout.

**Comment by cmeiklejohn** [comment]
```
  riak_kv_multi_backend: extra_callback_test...[0.262 s] ok
```

**Comment by reiddraper** [comment]
Gonna try this on another box, not sure why, but for me, it times out nearly every time.

**Comment by reiddraper** [comment]
@cmeiklejohn did you run the whole 'make test', or just this test? I'm only finding it time out when running the whole thing.

**Comment by cmeiklejohn** [comment]
I ran the entire suite.

**Comment by reiddraper** [comment]
It runs fine on my Linux box, so most just be some strange environment issues. Something that would be nice to fix eventually, but not gonna hold anything up. Closing for now.
