### ISSUE TITLE
Riak build is broken because of the lack of undefined callback function trusted/1 (behaviour 'riak_ensemble_backend')

### ISSUE THREAD

**Issue by pooya** [basho/riak_kv#901]
I was not sure if I should add it here or to the riak_ensemble repo.  But with commit
(https://github.com/basho/riak_ensemble/commit/812e0207909a267ca7c8b10619494d555536b7e5).
riak build is broken.  I saw the following error when I issued make rel in the clean riak repo. (erlan R16B02).

**Comment by jonmeredith** [comment]
Thanks, we'll fix today.

**Comment by jaredmorrow** [comment]
This is now fixed, sorry for the issues.
