### ISSUE TITLE
Violating vclock:dot opaque type

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_kv#903]
`riak_object:is_drop_candidate/2` peeks inside of a `dot()`, and dialzyer complains about this:

```
riak_object.erl:368: The call riak_object:is_drop_candidate(Dot::vclock:dot(),Drop::[{_,_}]) contains an opaque term as 1st argument when terms of different types are expected in these positions
```

Would it make sense for this function to just be moved into the vclock module?

**Comment by russelldb** [comment]
I know :(

**Comment by russelldb** [comment]
@reiddraper I don't think so, or I don't know, let me look into it. It was hack because riak is broken (two vclock entries can have the same {id, count} but a different timestamp) maybe we should fix that rather fundamental flaw, and leave this dialyzer bug as a open wound to remind us?

**Comment by russelldb** [comment]
But yes, I think some refactoring, to get `vclock` to destructure the dot would be good. I'll do it.

**Comment by russelldb** [comment]
Can't push to github, otherwise I'd push the fix to this.

**Comment by reiddraper** [comment]
Closing now that #910 was merged.
