### ISSUE TITLE
riak_kv_bitcask_backend dialyzer error

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_kv#905]
```
riak_kv_bitcask_backend.erl:600: Guard test Dir1TS::nonempty_string() == [] can never succeed
riak_kv_bitcask_backend.erl:602: Guard test Dir2TS::nonempty_string() == [] can never succeed
```

[The code](https://github.com/basho/riak_kv/blob/bb6502bab9eb4bd82a82053b2693417ec7b549ee/src/riak_kv_bitcask_backend.erl#L614-L639) is a bit hairy, so I'd like some better review here than just one commit stuck inside a bunch of dialyzer fixes. cc @kellymclaughlin who I believe wrote the original code. It looks so me like these two pattern matches will just never match, and we've likely always been falling through into the catch expression.

**Comment by engelsanchez** [comment]
This old migration code is being removed completely here: https://github.com/basho/riak_kv/pull/925.  I will close this and dialyzer problems can be handled on that PR. Re-open if you disagree Reid.

**Comment by reiddraper** [comment]
+1, thanks @engelsanchez
