### ISSUE TITLE
riak_kv_ensemble_backend syncing should check sibling peers

### ISSUE THREAD

**Issue by jtuple** [basho/riak_kv#908]
As currently written, `riak_kv_ensemble_backend` only considers a sync to be valid if AAE has been performed with the list of peers that initially responded to the sync request. If one of those peers becomes partitioned / goes offline, then `riak_kv_ensemble_backend:wait_for_sync` will loop until that peer returns.

One approach would be to change `wait_for_sync` to accept syncing with any majority of sibling peers. This seems safe since `riak_ensemble_peer:check_sync` will verify that the returned majority is trusted after the fact. However, there may be corner cases in this approach. I believe it is intentional that we check for trust both before and after, so ignoring the before check seems unwise.

I think the best approach is monitoring the set of peers that the current peer wants to sync with. Either by using a `monitor` or performing some sort of ping or node watcher check. In either case, `wait_for_sync` should fail the sync if it ever discovers it cannot communicate to all the peers it wants to.

When the sync fails, `riak_ensemble_peer` will send new sync requests, which can hit a different set of alive/trusted peers, ending up back in `wait_for_sync` with the new set to sync with.

/cc basho/riak#536

**Comment by reiddraper** [comment]
Is this still a 2.0-RC task?

**Comment by jtuple** [comment]
Yes. Everything on [this list](https://github.com/basho/riak/issues/536) is still a 2.0 RC task.

**Comment by jtuple** [comment]
This work is no longer necessary given changes made in basho/riak_ensemble#37. Closing issue.
