### ISSUE TITLE
Make consistency trust configurable

### ISSUE THREAD

**Issue by jtuple** [basho/riak_kv#909]
There should be configurable trust levels for consistent K/V data, or as I've called them in previous discussion levels of paranoia. Before `2.0.0beta1`, the `riak_kv_ensemble_backend` always trusted backend data. After `beta1`, the backend never trusts backend data. This should be user configurable.

This level of trust directly affects the availability properties of strongly consistent Riak.

Currently, we never trust backend data after a node / vnode restarts. This means that a given peer must sync with a majority of peers (not including itself) before it can vote in a quorum. For `N=3`, this means that no nodes can ever be offline. If a replica is offline, all associated quorums will be unavailable. For `N=5`, we would need 4 replicas online at all times. For `N=7` we would need 5 replicas online at all times. This is more restrictive then pure quorum because we're assuming byzantine disk faults in the maximum paranoia setting -- eg. undetected lost of data by disk, eg. data that we previously wrote to disk but the disk has since forgotten about without Riak realizing, eg. data loss that CRC/etc never detects.

At the lower paranoia setting, we trust the disks. And normal quorum requirements apply. In other worlds, `N=3` can tolerate 1 node offline, `N=5` can tolerate 2, `N=7` can tolerate 3, etc.

Once we make this configurable, we need to determine the default. I highly suggest we ship with maximum paranoia (the current hardcoded setting as of `beta1`) and suggest users use `N=5` or `N=7` for consistent data.

Users that trust their disks (eg. ZFS mirroring or better), that are certain they will never accidentally delete Riak data by hand, that are certain they'll never accidentally partially restore from an old backup, etc can choose to go with the lower paranoia setting and have the lower quorum requirements.

A more concrete example of what these levels of paranoia are solving is discussed [here](https://gist.github.com/jtuple/8611559).

Remember that this is addressing a limitation that many consistent systems the world over gloss over. That just because you write data to disk doesn't mean that data is still there in the future, and that you may never realize it went missing. Since Riak is designed for maximum data protection, we should ship with the strong settings (IMO).

---

Making this configurable is easy. It's essentially a 1 or 2 line change to `riak_kv_ensemble_backend:trusted` to return `true` or `false` based on an `app.config` setting.

/cc basho/riak#536

**Comment by reiddraper** [comment]
@jtuple is this still a 2.0-RC task?

**Comment by jtuple** [comment]
Yes. Everything on [this list](https://github.com/basho/riak/issues/536) is still a 2.0 RC task.

**Comment by engelsanchez** [comment]
Fixed by #980
