### ISSUE TITLE
put fsm can get a remote coordinator ack in any state and must be able to handle it.

### ISSUE THREAD

**Issue by evanmcc** [basho/riak_kv#912]
In perf regression testing I was running into an issue on a node that has some sort of disk problem causing high latencies and iowait.  This was causing a scheduler collapse on the node, which was causing extremely long sidejob worker queues.  

This new failure case is caused by the changes in https://github.com/basho/riak_kv/pull/627

The logic works something like this:
1. Long sidejob queues/collapse on node A are causing a > 3s delay on the remote spawn and ack process.
2. Node B, which got the original request, is # 4 on the preflist (for example).  It removes node A from the preflist, and becomes # 3, and so handles coordination itself, see: https://github.com/basho/riak_kv/blob/2.0.0beta1/src/riak_kv_put_fsm.erl#L325-L327
3. Node A finally processes the spawn and sends the ack message to B.
4. B is now no longer waiting for that particular message, which isn't handled else where in the fsm, causing the crash abbreviated below.

```
2014-04-15 04:53:16 =CRASH REPORT====
  crasher:
    initial call: riak_kv_put_fsm:init/1
    pid: <0.6330.1029>
    registered_name: []
    exception exit: {badmsg,[{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,622}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [riak_kv_put_fsm_sj_2,riak_kv_put_fsm_sj_worker_sup,riak_kv_put_fsm_sj,sidejob_sup,<0.463.0>]
    messages: []
    links: [<0.502.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1164
  neighbours:
2014-04-15 04:53:16 =ERROR REPORT====
** State machine <0.2474.1029> terminating 
** Last message in was {ack,'riak@10.0.24.40',now_executing}
** When State == validate
**      Data  == {state,{raw,7430680,<0.30606.990>},{r_object,<<"testbucket">>,<<0,32,48,191>>,[  ]}
** Reason for termination = 
** badmsg

```

also, it seems that we can get this message in more or less any state:

```
$ grep -h 'State ==' log-10.0.24.44/crash.log*  | sort | uniq
** When State == finish
** When State == postcommit
** When State == precommit
** When State == validate
** When State == waiting_local_vnode
** When State == waiting_remote_vnode
```

**Comment by jrwest** [comment]
just for extra detail: this issue can cause the sibling generation described [here](https://github.com/basho/riak_kv/pull/627#issuecomment-24638378)

**Comment by reiddraper** [comment]
What's the status here? @evanmcc @jrwest?

**Comment by evanmcc** [comment]
has been reviewed, @slfritchie's patch addresses this, but I don't think it's merged.

**Comment by reiddraper** [comment]
@evanmcc great. I just told borshop to merge #913. I'll close this once it's all merged in. Thanks.

**Comment by reiddraper** [comment]
#913 has merged. Closing.
