### ISSUE TITLE
Forward-port #940 to 2.0

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_kv#948]
@evanmcc let me know if I'm misunderstanding. I created this to put something on the 2.0 milestone, so #940 can remain on the 1.4.9 milestone.

**Comment by reiddraper** [comment]
@evanmcc did you say this ended up not being needed?

**Comment by evanmcc** [comment]
No, it still needs to go in.  I started poking at getting 1.4 compiling
cleanly again and then the world exploded.  I'll get it in and tested this
week.

**Comment by reiddraper** [comment]
Cool, thanks.

**Comment by kellymclaughlin** [comment]
#963 is merged, closing
