### ISSUE TITLE
List keys using unicode bucket type+name fails on Bitcask

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_kv#960]
Running the bucket_types riak_test using the bitcask backend results in a failure on line https://github.com/basho/riak_test/blob/a07018cb4cb76dacd3f0c8ac07185439a542e7c9/tests/bucket_types.erl#L149.  The list keys operation returns an empty list instead of the expected single <<"key">>. This test runs fine using LevelDB as the backend, which is what we do in GiddyUp.

**Comment by engelsanchez** [comment]
Scratch that. It seems to happen intermittently on either backend.

**Comment by engelsanchez** [comment]
BTW, I am currently looking at this issue.

**Comment by engelsanchez** [comment]
After some debugging, it turns out the root cause is a race between activation of a bucket type and putting a value into a bucket under it. Just like https://github.com/basho/riak_kv/issues/872.  In here, one of the 3 vnodes gets an {error, no_type} when trying to fetch the bucket properties on a put and fails to write.  Since the test reads the value before folding, read repair + the random coverage of the fold operations means that most of the time the test passes.  I'm going to stop looking at this test for the moment as the race is documented.  Hopefully we'll fix that soon.

**Comment by engelsanchez** [comment]
BTW, if #872 is moved out of the 2.0RC milestone, so should this issue.

**Comment by slfritchie** [comment]
If the propagation of bucket type info is an eventual thing, then this kind of race is going to happen.  So we ought to do something sane when the race does happen.  So, we should fall back to untyped(*) defaults, right?

(*) Where the "type" in "untyped" means bucket types.

**Comment by jrwest** [comment]
yes it is asynchronous, see: https://github.com/basho/riak_core/blob/develop/src/riak_core_bucket_type.erl#L34-L43

**Comment by engelsanchez** [comment]
I'm going to close this issue now since the handling of bucket types before they are ready can continue in #872 and making Riak tests more robust to this race is taken care of in basho/riak_test#630
