### ISSUE TITLE
The AAE throttle should be disabled along with AAE

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak_kv#969]
It is confusing to customers not using AAE to see the AAE vnode throttle messages. It would be better to disable the throttle by default when AAE is set to `off`.

Also, the `set_aae_throttle_kill` function name is confusing. It would be better to call this toggling function `enable_aae_throttle`.

**Comment by binarytemple** [comment]
+1 to fix this - also seen in- https://basho.zendesk.com/agent/#/tickets/8197

**Comment by rzezeski** [comment]
@bsparrow435 I linked a PR that attempts to fix the main issue in this ticket.

**Comment by engelsanchez** [comment]
I believe his rate is a six-pack of Boh per PR.

**Comment by rzezeski** [comment]
@engelsanchez I made this fix after @tsantero complained about it on IRC.  So he owes me the sixer.

**Comment by tsantero** [comment]
no payment will be issued until after this pr passes all tests and is merged

**Comment by slfritchie** [comment]
Hiya, @rzezeski, many thanks for the summer PR!  Had I known that I'd piss so many people off with the timing of that message, I'd added even more messages to write myself an entire case.  Or keg, even!

**Comment by rzezeski** [comment]
@slfritchie ありがとう Fritchie-san, for the quick review.
