### ISSUE TITLE
riak_kv_ensemble_backend should monitor vnode proxy

### ISSUE THREAD

**Issue by jtuple** [basho/riak_kv#985]
The K/V ensembles (as implemented in `riak_kv_ensemble_backend`) send bare messages to the vnode proxy without accounting for the fact that the proxy or vnode may crash. This can cause ensemble worker processes to stall indefinitely waiting for `local_get` and `local_put` replies. In practice, these requests will timeout (unless the user configures timeout = infinity -- which would be bad), but we should fail faster. Likewise, it's unclear if there are other proxy/vnode messages that are problematic (and which don't have timeouts).

To solve this properly, `riak_kv_ensemble_backend` should monitor the proxy and vnode, and when notice either crashing do something. That action could range from calling `exit()` and thus killing the ensemble peer (easiest), to sending a message to the ensemble peer that causes it to move to `probe` as well as restart all worker processes just to be safe.

We don't want to use a `link` since that will make crashes of the peer propagate to the proxy/vnode.

My suggested solution is to extend the `riak_ensemble_backend` behavior to have a new `handle_down` (or similarly named) callback that returns `true/false`. Then have `riak_ensemble_peer` invoke this callback in `handle_info('DOWN',...)`. If the callback returns true, that means the backend handled the message, if false then `riak_ensemble_peer` does it's normal `maybe_restart_workers` check (that handles monitors fired from failed workers). 

We then extend `riak_kv_ensemble_backend` to monitor the proxy and vnode in `init`, track those monitor refs, and implement a `handle_down` callback that reacts if the relevant monitor fired (or returns false otherwise).

/cc basho/riak#536

**Comment by andrewjstone** [comment]
Test is here: basho/riak_test#645
Test requires these PRs:
- basho/riak_ensemble#33
- basho/riak_kv#990

**Comment by andrewjstone** [comment]
All PRs have been merged. closing.
