### ISSUE TITLE
Implement overload replies for ensemble messages

### ISSUE THREAD

**Issue by jtuple** [basho/riak_kv#986]
The K/V ensembles (as implemented in riak_kv_ensemble_backend) send bare messages to the vnode proxy without accounting for the fact that the proxy may drop those messages on the floor in an overload scenario. This can cause ensemble worker processes to stall indefinitely waiting for local_get and local_put replies. In practice, these requests will timeout (unless the user configures timeout = infinity -- which would be bad), but we should fail faster. Likewise, it's unclear if there are other proxy/vnode messages that are problematic (and which don't have timeouts).

We should extend `riak_kv_vnode:handle_overload_command` to account for all ensemble related messages and send a timeout/overload response back.

Note: unlike normal K/V messages that send a reply using `riak_core_vnode:reply`, ensemble messages are handled differently. Make sure to check the various ensemble commands in `handle_info(....)` to see how replies are meant to be sent back to the ensemble peer. In most (all?) cases, this is via a call to `riak_kv_ensemble_backend:reply`. In any case, easy to just copy the appropriate message pattern message and reply approach from the relevant `handle_info(...)` code.

/cc basho/riak#536

**Comment by andrewjstone** [comment]
Fixed by #994 and basho/riak_core#605
