### ISSUE TITLE
Strong consistency AAE check broken

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_kv#988]
The current check to see if AAE is enabled in riak_kv_ensembles is expecting riak_kv/anti_entropy to be on, but this parameter is funky and is actually {on, []} or {on, [debug]}.  So the warning in the logs happens even if all things are good:

```
2014-06-17 12:00:05.829 [warning] <0.384.0>@riak_kv_ensembles:maybe_aae_configuration_valid:168 Strong consistency has been enabled without AAE -- all consistent operations will timeout until AAE is enabled.
```

/cc @jburwell

**Comment by engelsanchez** [comment]
Well, I'm going to take this myself. It should be hopefully quick.

**Comment by engelsanchez** [comment]
basho/riak_kv#993 is a proposed fix for this

**Comment by jburwell** [comment]
I re-tested the [riaknostic strong consistency check](https://github.com/basho/riaknostic/blob/develop/src/riaknostic_check_strong_consistency.erl) to ensure that the pattern match was not too loose and mis-reported the warning.  Tests passed for the following scenarios:
- anti_entropy: passive; strong_consistency: off
- anti_entropy: active; strong_consistency: off
- anti_entropy: active-debug; strong_consistency: off
- anti_entropy: passive; strong_consistency: on
- anti_entropy: active; strong_consistency: on
- anti_entropy: active-debug; strong_consistency: on

The warning message was only reported in the anti_entry: passive; strong_consistency: on scenario.
